ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_title VARCHAR(200);
ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_description VARCHAR(500);
ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_image_url VARCHAR(500);
