-- V77: Replace hero-carousel slides with the 9 real SSSY images
--      copied to /public/images/slider/.
--      Each backgroundImage is a Next.js public-folder path served at runtime.
--
-- NOTE: Arabic text is written as literal UTF-8 (no \u escapes) so that
--       PostgreSQL can parse this file correctly regardless of client_encoding.

DELETE FROM flyway_schema_history
WHERE version = '77' AND success = FALSE;

UPDATE site_sections
SET
  -- Update BOTH the draft AND the published snapshot so the live homepage
  -- (which reads published_config first) shows the new images immediately.
  config = jsonb_set(
    config,
    '{slides}',
    $slides$
    [
      {
        "titleEn": "Syrian Soil Science Society",
        "titleAr": "جمعية علوم التربة السورية",
        "subtitleEn": "Advancing Knowledge - Protecting Land",
        "subtitleAr": "تطوير المعرفة - حماية الأرض",
        "badgeLabelEn": "Welcome",
        "badgeLabelAr": "أهلاً وسهلاً",
        "descriptionEn": "A leading scientific community dedicated to soil research, sustainable land management, and advancing agricultural science across Syria and the Arab world.",
        "descriptionAr": "مجتمع علمي رائد مكرّس لأبحاث التربة وإدارة الأراضي المستدامة وتطوير العلوم الزراعية في سوريا والعالم العربي.",
        "primaryButtonLabelEn": "Join the Society",
        "primaryButtonLabelAr": "انضم للجمعية",
        "primaryButtonUrl": "/members",
        "secondaryButtonLabelEn": "Explore Research",
        "secondaryButtonLabelAr": "استكشف الأبحاث",
        "secondaryButtonUrl": "/publications",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.16.43 PM.jpeg",
        "overlayColor": "rgba(18,42,18,0.70)"
      },
      {
        "titleEn": "Laboratory Research",
        "titleAr": "البحث المختبري",
        "subtitleEn": "Precision Soil Analysis",
        "subtitleAr": "تحليل دقيق للتربة",
        "badgeLabelEn": "Research",
        "badgeLabelAr": "بحث علمي",
        "descriptionEn": "Our researchers pioneer innovative approaches to soil analysis, classification, and conservation - building a sustainable future for Syrian agriculture.",
        "descriptionAr": "يرتاد باحثونا أساليب مبتكرة في تحليل التربة وتصنيفها وصونها.",
        "primaryButtonLabelEn": "View Publications",
        "primaryButtonLabelAr": "عرض المنشورات",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Our Members",
        "secondaryButtonLabelAr": "أعضاؤنا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/Gemini_Generated_Image_hnvytbhnvytbhnvy.png",
        "overlayColor": "rgba(10,28,48,0.68)"
      },
      {
        "titleEn": "Advanced Soil Mapping",
        "titleAr": "رسم خرائط التربة المتقدم",
        "subtitleEn": "Data-Driven Land Management",
        "subtitleAr": "إدارة الأراضي بالبيانات",
        "badgeLabelEn": "Innovation",
        "badgeLabelAr": "ابتكار",
        "descriptionEn": "Cutting-edge GIS and remote sensing technologies map Syria's agricultural landscape for informed land-use decisions.",
        "descriptionAr": "تقنيات نظم المعلومات الجغرافية والاستشعار عن بعد ترسم المشهد الزراعي في سوريا.",
        "primaryButtonLabelEn": "Upcoming Events",
        "primaryButtonLabelAr": "الفعاليات القادمة",
        "primaryButtonUrl": "/events",
        "secondaryButtonLabelEn": "Publications",
        "secondaryButtonLabelAr": "المنشورات",
        "secondaryButtonUrl": "/publications",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-24 at 1.32.59 PM.jpeg",
        "overlayColor": "rgba(15,30,50,0.72)"
      },
      {
        "titleEn": "Modern Soil Laboratory",
        "titleAr": "مختبر تربة حديث",
        "subtitleEn": "State-of-the-Art Facilities",
        "subtitleAr": "معدات على أحدث مستوى",
        "badgeLabelEn": "Laboratory",
        "badgeLabelAr": "مختبر",
        "descriptionEn": "Our fully equipped modern laboratories enable precise chemical and physical analysis of soil samples from across Syria.",
        "descriptionAr": "مختبراتنا الحديثة المجهزة بالكامل تتيح تحليلاً كيميائياً وفيزيائياً دقيقاً لعينات التربة.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-26 at 10.18.58 PM.jpeg",
        "overlayColor": "rgba(8,25,50,0.65)"
      },
      {
        "titleEn": "Soil Research Laboratory",
        "titleAr": "مختبر أبحاث التربة",
        "subtitleEn": "Analysis - Classification - Conservation",
        "subtitleAr": "تحليل - تصنيف - صون",
        "badgeLabelEn": "Field & Lab",
        "badgeLabelAr": "حقل ومختبر",
        "descriptionEn": "Integrating field sampling with laboratory analysis, our scientists develop comprehensive soil databases for Syria's diverse regions.",
        "descriptionAr": "بدمج أخذ العينات الحقلية مع التحليل المختبري، يطور علماؤنا قواعد بيانات شاملة للتربة.",
        "primaryButtonLabelEn": "View Publications",
        "primaryButtonLabelAr": "عرض المنشورات",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Join Us",
        "secondaryButtonLabelAr": "انضم إلينا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-26 at 10.39.05 PM.jpeg",
        "overlayColor": "rgba(20,35,10,0.65)"
      },
      {
        "titleEn": "Microscopic Soil Analysis",
        "titleAr": "تحليل التربة بالمجهر",
        "subtitleEn": "From Micro to Macro",
        "subtitleAr": "من المجهري إلى الكلي",
        "badgeLabelEn": "Microscopy",
        "badgeLabelAr": "مجهرية",
        "descriptionEn": "Microscopic examination of soil microstructure reveals hidden biological and mineral interactions that govern fertility and crop yield.",
        "descriptionAr": "الفحص المجهري لبنية التربة يكشف التفاعلات الحيوية والمعدنية الخفية التي تحكم الخصوبة.",
        "primaryButtonLabelEn": "Our Research",
        "primaryButtonLabelAr": "أبحاثنا",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-02-10 at 1.28.37 PM.jpeg",
        "overlayColor": "rgba(10,10,30,0.65)"
      },
      {
        "titleEn": "Soil Profile & Classification",
        "titleAr": "ملف التربة والتصنيف",
        "subtitleEn": "Understanding Soil Horizons",
        "subtitleAr": "فهم طبقات التربة",
        "badgeLabelEn": "Education",
        "badgeLabelAr": "تعليم",
        "descriptionEn": "From the organic O-horizon to bedrock - understanding soil profiles is fundamental to sustainable agriculture and land planning.",
        "descriptionAr": "من طبقة O العضوية حتى الصخر الأساسي - فهم ملفات التربة أساس الزراعة المستدامة.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.19.25 PM.jpeg",
        "overlayColor": "rgba(25,55,15,0.55)"
      },
      {
        "titleEn": "Soil Layers & Structure",
        "titleAr": "طبقات التربة وبنيتها",
        "subtitleEn": "From Humus to Bedrock",
        "subtitleAr": "من الدبال إلى الصخر الأساسي",
        "badgeLabelEn": "Science",
        "badgeLabelAr": "علم",
        "descriptionEn": "Comprehensive soil horizon studies - from organic humus layers to bedrock - informing land-use planning across Syrian territories.",
        "descriptionAr": "دراسات شاملة لطبقات التربة - من طبقة الدبال العضوية حتى طبقة الصخر الأساسي.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.20.10 PM.jpeg",
        "overlayColor": "rgba(30,55,10,0.55)"
      },
      {
        "titleEn": "Soil Types & Diversity",
        "titleAr": "أنواع التربة وتنوعها",
        "subtitleEn": "Mapping Syria's Soils",
        "subtitleAr": "رسم خريطة ترب سوريا",
        "badgeLabelEn": "Field Study",
        "badgeLabelAr": "دراسة ميدانية",
        "descriptionEn": "From dark humus-rich soils to sandy loam - Syria's diverse soil types support a wide range of crops and require specialised management.",
        "descriptionAr": "من الترب الغنية بالدبال الداكنة إلى الرمال الطينية - تدعم ترب سوريا المتنوعة مجموعة واسعة من المحاصيل.",
        "primaryButtonLabelEn": "Soil Research",
        "primaryButtonLabelAr": "أبحاث التربة",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Join Us",
        "secondaryButtonLabelAr": "انضم إلينا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.20.39 PM.jpeg",
        "overlayColor": "rgba(42,30,10,0.60)"
      }
    ]
    $slides$::jsonb
  ),
  published_config = jsonb_set(
    COALESCE(published_config, config, '{}'),
    '{slides}',
    $slides$
    [
      {
        "titleEn": "Syrian Soil Science Society",
        "titleAr": "جمعية علوم التربة السورية",
        "subtitleEn": "Advancing Knowledge - Protecting Land",
        "subtitleAr": "تطوير المعرفة - حماية الأرض",
        "badgeLabelEn": "Welcome",
        "badgeLabelAr": "أهلاً وسهلاً",
        "descriptionEn": "A leading scientific community dedicated to soil research, sustainable land management, and advancing agricultural science across Syria and the Arab world.",
        "descriptionAr": "مجتمع علمي رائد مكرّس لأبحاث التربة وإدارة الأراضي المستدامة وتطوير العلوم الزراعية في سوريا والعالم العربي.",
        "primaryButtonLabelEn": "Join the Society",
        "primaryButtonLabelAr": "انضم للجمعية",
        "primaryButtonUrl": "/members",
        "secondaryButtonLabelEn": "Explore Research",
        "secondaryButtonLabelAr": "استكشف الأبحاث",
        "secondaryButtonUrl": "/publications",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.16.43 PM.jpeg",
        "overlayColor": "rgba(18,42,18,0.70)"
      },
      {
        "titleEn": "Laboratory Research",
        "titleAr": "البحث المختبري",
        "subtitleEn": "Precision Soil Analysis",
        "subtitleAr": "تحليل دقيق للتربة",
        "badgeLabelEn": "Research",
        "badgeLabelAr": "بحث علمي",
        "descriptionEn": "Our researchers pioneer innovative approaches to soil analysis, classification, and conservation - building a sustainable future for Syrian agriculture.",
        "descriptionAr": "يرتاد باحثونا أساليب مبتكرة في تحليل التربة وتصنيفها وصونها.",
        "primaryButtonLabelEn": "View Publications",
        "primaryButtonLabelAr": "عرض المنشورات",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Our Members",
        "secondaryButtonLabelAr": "أعضاؤنا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/Gemini_Generated_Image_hnvytbhnvytbhnvy.png",
        "overlayColor": "rgba(10,28,48,0.68)"
      },
      {
        "titleEn": "Advanced Soil Mapping",
        "titleAr": "رسم خرائط التربة المتقدم",
        "subtitleEn": "Data-Driven Land Management",
        "subtitleAr": "إدارة الأراضي بالبيانات",
        "badgeLabelEn": "Innovation",
        "badgeLabelAr": "ابتكار",
        "descriptionEn": "Cutting-edge GIS and remote sensing technologies map Syria's agricultural landscape for informed land-use decisions.",
        "descriptionAr": "تقنيات نظم المعلومات الجغرافية والاستشعار عن بعد ترسم المشهد الزراعي في سوريا.",
        "primaryButtonLabelEn": "Upcoming Events",
        "primaryButtonLabelAr": "الفعاليات القادمة",
        "primaryButtonUrl": "/events",
        "secondaryButtonLabelEn": "Publications",
        "secondaryButtonLabelAr": "المنشورات",
        "secondaryButtonUrl": "/publications",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-24 at 1.32.59 PM.jpeg",
        "overlayColor": "rgba(15,30,50,0.72)"
      },
      {
        "titleEn": "Modern Soil Laboratory",
        "titleAr": "مختبر تربة حديث",
        "subtitleEn": "State-of-the-Art Facilities",
        "subtitleAr": "معدات على أحدث مستوى",
        "badgeLabelEn": "Laboratory",
        "badgeLabelAr": "مختبر",
        "descriptionEn": "Our fully equipped modern laboratories enable precise chemical and physical analysis of soil samples from across Syria.",
        "descriptionAr": "مختبراتنا الحديثة المجهزة بالكامل تتيح تحليلاً كيميائياً وفيزيائياً دقيقاً لعينات التربة.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-26 at 10.18.58 PM.jpeg",
        "overlayColor": "rgba(8,25,50,0.65)"
      },
      {
        "titleEn": "Soil Research Laboratory",
        "titleAr": "مختبر أبحاث التربة",
        "subtitleEn": "Analysis - Classification - Conservation",
        "subtitleAr": "تحليل - تصنيف - صون",
        "badgeLabelEn": "Field & Lab",
        "badgeLabelAr": "حقل ومختبر",
        "descriptionEn": "Integrating field sampling with laboratory analysis, our scientists develop comprehensive soil databases for Syria's diverse regions.",
        "descriptionAr": "بدمج أخذ العينات الحقلية مع التحليل المختبري، يطور علماؤنا قواعد بيانات شاملة للتربة.",
        "primaryButtonLabelEn": "View Publications",
        "primaryButtonLabelAr": "عرض المنشورات",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Join Us",
        "secondaryButtonLabelAr": "انضم إلينا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-03-26 at 10.39.05 PM.jpeg",
        "overlayColor": "rgba(20,35,10,0.65)"
      },
      {
        "titleEn": "Microscopic Soil Analysis",
        "titleAr": "تحليل التربة بالمجهر",
        "subtitleEn": "From Micro to Macro",
        "subtitleAr": "من المجهري إلى الكلي",
        "badgeLabelEn": "Microscopy",
        "badgeLabelAr": "مجهرية",
        "descriptionEn": "Microscopic examination of soil microstructure reveals hidden biological and mineral interactions that govern fertility and crop yield.",
        "descriptionAr": "الفحص المجهري لبنية التربة يكشف التفاعلات الحيوية والمعدنية الخفية التي تحكم الخصوبة.",
        "primaryButtonLabelEn": "Our Research",
        "primaryButtonLabelAr": "أبحاثنا",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-02-10 at 1.28.37 PM.jpeg",
        "overlayColor": "rgba(10,10,30,0.65)"
      },
      {
        "titleEn": "Soil Profile & Classification",
        "titleAr": "ملف التربة والتصنيف",
        "subtitleEn": "Understanding Soil Horizons",
        "subtitleAr": "فهم طبقات التربة",
        "badgeLabelEn": "Education",
        "badgeLabelAr": "تعليم",
        "descriptionEn": "From the organic O-horizon to bedrock - understanding soil profiles is fundamental to sustainable agriculture and land planning.",
        "descriptionAr": "من طبقة O العضوية حتى الصخر الأساسي - فهم ملفات التربة أساس الزراعة المستدامة.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.19.25 PM.jpeg",
        "overlayColor": "rgba(25,55,15,0.55)"
      },
      {
        "titleEn": "Soil Layers & Structure",
        "titleAr": "طبقات التربة وبنيتها",
        "subtitleEn": "From Humus to Bedrock",
        "subtitleAr": "من الدبال إلى الصخر الأساسي",
        "badgeLabelEn": "Science",
        "badgeLabelAr": "علم",
        "descriptionEn": "Comprehensive soil horizon studies - from organic humus layers to bedrock - informing land-use planning across Syrian territories.",
        "descriptionAr": "دراسات شاملة لطبقات التربة - من طبقة الدبال العضوية حتى طبقة الصخر الأساسي.",
        "primaryButtonLabelEn": "Learn More",
        "primaryButtonLabelAr": "اقرأ المزيد",
        "primaryButtonUrl": "/news",
        "secondaryButtonLabelEn": "Contact Us",
        "secondaryButtonLabelAr": "تواصل معنا",
        "secondaryButtonUrl": "/contact",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.20.10 PM.jpeg",
        "overlayColor": "rgba(30,55,10,0.55)"
      },
      {
        "titleEn": "Soil Types & Diversity",
        "titleAr": "أنواع التربة وتنوعها",
        "subtitleEn": "Mapping Syria's Soils",
        "subtitleAr": "رسم خريطة ترب سوريا",
        "badgeLabelEn": "Field Study",
        "badgeLabelAr": "دراسة ميدانية",
        "descriptionEn": "From dark humus-rich soils to sandy loam - Syria's diverse soil types support a wide range of crops and require specialised management.",
        "descriptionAr": "من الترب الغنية بالدبال الداكنة إلى الرمال الطينية - تدعم ترب سوريا المتنوعة مجموعة واسعة من المحاصيل.",
        "primaryButtonLabelEn": "Soil Research",
        "primaryButtonLabelAr": "أبحاث التربة",
        "primaryButtonUrl": "/publications",
        "secondaryButtonLabelEn": "Join Us",
        "secondaryButtonLabelAr": "انضم إلينا",
        "secondaryButtonUrl": "/members",
        "backgroundImage": "/images/slider/WhatsApp Image 2026-07-26 at 12.20.39 PM.jpeg",
        "overlayColor": "rgba(42,30,10,0.60)"
      }
    ]
    $slides$::jsonb
  ),
  published_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE slug = 'hero-banner'
  AND component_type = 'hero-carousel';
