/**
 * section-templates.ts
 * Pre-built section template definitions with bilingual placeholder content.
 * Each template ships with full EN + AR defaults ready to use.
 */

export type TemplateCategory =
  | 'Hero'
  | 'Content'
  | 'Cards'
  | 'Statistics'
  | 'Media'
  | 'Forms'
  | 'Dynamic'
  | 'Pricing'
  | 'Portfolio'
  | 'Blog'
  | 'Features'
  | 'Team'
  | 'Testimonials'
  | 'Gallery'
  | 'Video'
  | 'Maps'
  | 'Steps'
  | 'Logos'
  | 'Tabs'
  | 'Comparison'
  | 'Custom';

export interface SectionTemplate {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  componentType: string;
  category: TemplateCategory;
  defaultData: Record<string, unknown>;
  defaultConfig: Record<string, unknown>;
  defaultStyling: Record<string, unknown>;
}

export const SECTION_TEMPLATES: SectionTemplate[] = [
  // ── Hero ─────────────────────────────────────────────────────────────────
  {
    id: 'hero-standard',
    name: 'Hero Banner',
    nameAr: 'بانر رئيسي',
    description: 'Full-width hero with headline, description and two action buttons',
    descriptionAr: 'بانر كامل العرض مع عنوان ووصف وزرين للإجراءات',
    componentType: 'hero',
    category: 'Hero',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Welcome to the Soil Science Society of Syria',
      titleAr: 'مرحباً بكم في جمعية علوم التربة السورية',
      subtitleEn: 'Advancing Soil Science for a Sustainable Future',
      subtitleAr: 'تطوير علوم التربة من أجل مستقبل مستدام',
      descriptionEn: 'We are dedicated to promoting soil science research, education, and sustainable land management practices across Syria and the region.',
      descriptionAr: 'نحن ملتزمون بتعزيز أبحاث علوم التربة والتعليم وممارسات الإدارة المستدامة للأراضي في سوريا والمنطقة.',
      primaryButtonLabelEn: 'Explore Research',
      primaryButtonLabelAr: 'استكشف الأبحاث',
      primaryButtonUrl: '/publications',
      secondaryButtonLabelEn: 'Join Society',
      secondaryButtonLabelAr: 'انضم للجمعية',
      secondaryButtonUrl: '/membership',
      backgroundImage: '',
      bgColor: 'bg-gradient-hero',
    },
    defaultStyling: { paddingClass: 'py-24' },
  },
  {
    id: 'hero-carousel',
    name: 'Hero Carousel',
    nameAr: 'بانر دوّار',
    description: 'Auto-playing carousel of full-width hero slides',
    descriptionAr: 'كاروسيل يتشغّل تلقائياً من شرائح بانر كاملة العرض',
    componentType: 'hero-carousel',
    category: 'Hero',
    defaultData: {
      images: [
        {
          titleEn: 'Advancing Soil Science',
          titleAr: 'تطوير علوم التربة',
          descriptionEn: 'Leading research for sustainable agriculture',
          descriptionAr: 'أبحاث رائدة لزراعة مستدامة',
          image: '',
          buttonLabelEn: 'Learn More',
          buttonLabelAr: 'اعرف المزيد',
          buttonUrl: '/about',
        },
        {
          titleEn: 'Annual Symposium 2024',
          titleAr: 'الندوة السنوية 2024',
          descriptionEn: 'Join us for the latest in soil science research',
          descriptionAr: 'انضم إلينا لاستكشاف أحدث أبحاث علوم التربة',
          image: '',
          buttonLabelEn: 'Register Now',
          buttonLabelAr: 'سجّل الآن',
          buttonUrl: '/events',
        },
      ],
    },
    defaultConfig: { titleEn: 'Welcome', titleAr: 'أهلاً وسهلاً' },
    defaultStyling: {},
  },
  // ── Content ───────────────────────────────────────────────────────────────
  {
    id: 'cta-join',
    name: 'Call to Action',
    nameAr: 'دعوة للعمل',
    description: 'Prominent CTA banner with headline and button',
    descriptionAr: 'بانر دعوة للعمل بارز مع عنوان وزر',
    componentType: 'cta',
    category: 'Content',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Join Our Community of Soil Scientists',
      titleAr: 'انضم إلى مجتمع علماء التربة',
      subtitleEn: 'Connect with leading researchers and practitioners across Syria',
      subtitleAr: 'تواصل مع الباحثين والممارسين الرائدين في سوريا',
      buttonLabelEn: 'Become a Member',
      buttonLabelAr: 'كن عضواً',
      buttonUrl: '/membership',
      bgColor: 'bg-forest',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-20' },
  },
  {
    id: 'banner-announcement',
    name: 'Announcement Banner',
    nameAr: 'بانر إعلاني',
    description: 'Full-width announcement or alert banner',
    descriptionAr: 'بانر إعلاني أو تنبيه كامل العرض',
    componentType: 'banner',
    category: 'Content',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Important Announcement',
      titleAr: 'إعلان مهم',
      bodyEn: 'The annual soil science symposium registration is now open. Limited seats available.',
      bodyAr: 'تسجيل الندوة السنوية لعلوم التربة مفتوح الآن. المقاعد محدودة.',
      buttonLabelEn: 'Register Now',
      buttonLabelAr: 'سجّل الآن',
      buttonUrl: '/events',
      bgColor: 'bg-soil-clay',
    },
    defaultStyling: {},
  },
  {
    id: 'faq-section',
    name: 'FAQ Section',
    nameAr: 'قسم الأسئلة الشائعة',
    description: 'Accordion-style frequently asked questions',
    descriptionAr: 'أسئلة شائعة بأسلوب الأكورديون',
    componentType: 'faq',
    category: 'Content',
    defaultData: {
      items: [
        {
          questionEn: 'How do I become a member?',
          questionAr: 'كيف أصبح عضواً؟',
          answerEn: 'You can apply for membership through our online portal. Fill out the application form and our team will review your request within 5–7 business days.',
          answerAr: 'يمكنك التقدم للعضوية من خلال بوابتنا الإلكترونية. املأ نموذج الطلب وسيراجع فريقنا طلبك خلال 5-7 أيام عمل.',
        },
        {
          questionEn: 'What are the membership benefits?',
          questionAr: 'ما هي مزايا العضوية؟',
          answerEn: 'Members enjoy access to our research library, discounted event registration, networking opportunities, and our monthly newsletter.',
          answerAr: 'يتمتع الأعضاء بالوصول إلى مكتبتنا البحثية وتسجيل الفعاليات بأسعار مخفضة وفرص التواصل ونشرتنا الإخبارية الشهرية.',
        },
        {
          questionEn: 'How can I submit my research?',
          questionAr: 'كيف يمكنني تقديم بحثي؟',
          answerEn: 'Research submissions can be made through the publications section. Please review our submission guidelines before submitting.',
          answerAr: 'يمكن تقديم الأبحاث من خلال قسم المنشورات. يرجى مراجعة إرشادات التقديم قبل الإرسال.',
        },
      ],
    },
    defaultConfig: {
      titleEn: 'Frequently Asked Questions',
      titleAr: 'الأسئلة الشائعة',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'timeline-section',
    name: 'Timeline',
    nameAr: 'جدول زمني',
    description: 'Vertical timeline for history, milestones or events',
    descriptionAr: 'جدول زمني رأسي للتاريخ والإنجازات أو الأحداث',
    componentType: 'timeline',
    category: 'Content',
    defaultData: {
      items: [
        { year: '1975', titleEn: 'Society Founded', titleAr: 'تأسيس الجمعية', descriptionEn: 'The Syrian Soil Science Society was established by a group of leading soil scientists.', descriptionAr: 'أُسِّست جمعية علوم التربة السورية على يد مجموعة من علماء التربة البارزين.' },
        { year: '1990', titleEn: 'First Annual Symposium', titleAr: 'أول ندوة سنوية', descriptionEn: 'Launch of our flagship annual symposium, now in its 34th year.', descriptionAr: 'إطلاق ندوتنا السنوية الرائدة، التي تقام الآن في عامها الرابع والثلاثين.' },
        { year: '2010', titleEn: 'Digital Research Portal', titleAr: 'بوابة الأبحاث الرقمية', descriptionEn: 'Launch of the online research and publication portal.', descriptionAr: 'إطلاق بوابة الأبحاث والنشر الإلكترونية.' },
        { year: '2024', titleEn: 'New Website Launch', titleAr: 'إطلاق الموقع الجديد', descriptionEn: 'Modern digital presence with full bilingual support.', descriptionAr: 'حضور رقمي حديث مع دعم كامل للغتين.' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our History',
      titleAr: 'تاريخنا',
    },
    defaultStyling: { bgColor: 'bg-soil-sand/20', paddingClass: 'py-16' },
  },
  // ── Cards ─────────────────────────────────────────────────────────────────
  {
    id: 'card-group-focus',
    name: 'Card Group',
    nameAr: 'مجموعة بطاقات',
    description: 'Grid of icon cards — ideal for features or focus areas',
    descriptionAr: 'شبكة من البطاقات الأيقونية — مثالية للميزات أو مجالات التركيز',
    componentType: 'card-group',
    category: 'Cards',
    defaultData: {
      items: [
        { icon: '🌱', titleEn: 'Soil Health', titleAr: 'صحة التربة', descriptionEn: 'Researching and promoting optimal soil health for agricultural productivity.', descriptionAr: 'البحث وتعزيز صحة التربة المثلى للإنتاجية الزراعية.' },
        { icon: '💧', titleEn: 'Water Management', titleAr: 'إدارة المياه', descriptionEn: 'Sustainable water use practices for dryland and irrigated agriculture.', descriptionAr: 'ممارسات الاستخدام المستدام للمياه في الزراعة البعلية والمروية.' },
        { icon: '🌾', titleEn: 'Crop Science', titleAr: 'علوم المحاصيل', descriptionEn: 'Connecting soil science with crop nutrition and yield optimization.', descriptionAr: 'ربط علوم التربة بتغذية المحاصيل وتحسين الغلة.' },
        { icon: '🔬', titleEn: 'Research', titleAr: 'الأبحاث', descriptionEn: 'Advancing scientific knowledge through rigorous soil research.', descriptionAr: 'تطوير المعرفة العلمية من خلال أبحاث التربة الدقيقة.' },
        { icon: '📚', titleEn: 'Education', titleAr: 'التعليم', descriptionEn: 'Training the next generation of soil scientists and land managers.', descriptionAr: 'تدريب الجيل القادم من علماء التربة ومديري الأراضي.' },
        { icon: '🤝', titleEn: 'Community', titleAr: 'المجتمع', descriptionEn: 'Building a collaborative network of soil science professionals.', descriptionAr: 'بناء شبكة تعاونية من المتخصصين في علوم التربة.' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Focus Areas',
      titleAr: 'مجالات تركيزنا',
      columns: 3,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'team-section',
    name: 'Team Grid',
    nameAr: 'شبكة الفريق',
    description: 'Photo grid of team members or board',
    descriptionAr: 'شبكة صور لأعضاء الفريق أو المجلس',
    componentType: 'team',
    category: 'Cards',
    defaultData: {
      members: [
        { nameEn: 'Dr. Ahmad Al-Rashid', nameAr: 'د. أحمد الراشد', roleEn: 'President', roleAr: 'الرئيس', bioEn: 'Leading soil scientist with 20+ years of experience.', bioAr: 'عالم تربة رائد يتمتع بخبرة تزيد على 20 عاماً.', photo: '' },
        { nameEn: 'Prof. Layla Hassan', nameAr: 'أ.د. ليلى حسن', roleEn: 'Vice President', roleAr: 'نائب الرئيس', bioEn: 'Expert in soil microbiology and ecosystem services.', bioAr: 'خبيرة في علم أحياء التربة الدقيقة وخدمات النظام البيئي.', photo: '' },
        { nameEn: 'Dr. Omar Khalil', nameAr: 'د. عمر خليل', roleEn: 'Secretary General', roleAr: 'الأمين العام', bioEn: 'Specializing in soil conservation and land degradation.', bioAr: 'متخصص في الحفاظ على التربة وتدهور الأراضي.', photo: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Leadership Team',
      titleAr: 'فريق قيادتنا',
    },
    defaultStyling: { bgColor: 'bg-soil-sand/10', paddingClass: 'py-16' },
  },
  // ── Statistics ────────────────────────────────────────────────────────────
  {
    id: 'stats-counter',
    name: 'Statistics Counter',
    nameAr: 'عدّاد الإحصائيات',
    description: 'Animated number counters for key metrics',
    descriptionAr: 'عدّادات أرقام متحركة للمقاييس الرئيسية',
    componentType: 'stats',
    category: 'Statistics',
    defaultData: {
      items: [
        { value: '500+', titleEn: 'Members', titleAr: 'عضو' },
        { value: '150+', titleEn: 'Research Papers', titleAr: 'ورقة بحثية' },
        { value: '30+', titleEn: 'Years of Service', titleAr: 'عاماً من الخدمة' },
        { value: '20+', titleEn: 'Partner Institutions', titleAr: 'مؤسسة شريكة' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Impact in Numbers',
      titleAr: 'أثرنا بالأرقام',
      bgColor: 'bg-soil-dark',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-16' },
  },
  // ── Media ─────────────────────────────────────────────────────────────────
  {
    id: 'testimonials-section',
    name: 'Testimonials',
    nameAr: 'شهادات',
    description: 'Member testimonials and quotes',
    descriptionAr: 'شهادات واقتباسات الأعضاء',
    componentType: 'testimonials',
    category: 'Media',
    defaultData: {
      items: [
        { nameEn: 'Dr. Sami Barakat', nameAr: 'د. سامي بركات', roleEn: 'Research Scientist', roleAr: 'باحث علمي', quoteEn: 'The SSSY has been instrumental in connecting me with leading researchers and advancing my career.', quoteAr: 'كانت جمعية SSSY أداةً فعّالة في ربطي بالباحثين الرائدين وتطوير مسيرتي المهنية.', avatar: '' },
        { nameEn: 'Eng. Rania Youssef', nameAr: 'م. رانيا يوسف', roleEn: 'Agricultural Engineer', roleAr: 'مهندسة زراعية', quoteEn: 'The annual symposium is a highlight of my professional calendar every year.', quoteAr: 'الندوة السنوية هي حدث بارز في تقويمي المهني كل عام.', avatar: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'What Our Members Say',
      titleAr: 'ماذا يقول أعضاؤنا',
    },
    defaultStyling: { bgColor: 'bg-soil-sand/20', paddingClass: 'py-16' },
  },
  {
    id: 'publications-carousel',
    name: 'Publications Carousel',
    nameAr: 'كاروسيل المنشورات',
    description: 'Scrolling carousel of recent publications',
    descriptionAr: 'كاروسيل قابل للتمرير للمنشورات الأخيرة',
    componentType: 'publications-carousel',
    category: 'Media',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Recent Publications',
      titleAr: 'المنشورات الأخيرة',
      viewAllLabelEn: 'View All Publications',
      viewAllLabelAr: 'عرض جميع المنشورات',
      viewAllUrl: '/publications',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  // ── Forms ─────────────────────────────────────────────────────────────────
  {
    id: 'newsletter-signup',
    name: 'Newsletter Signup',
    nameAr: 'الاشتراك في النشرة',
    description: 'Email newsletter subscription section',
    descriptionAr: 'قسم الاشتراك في النشرة الإخبارية',
    componentType: 'newsletter',
    category: 'Forms',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Stay Updated with Soil Science',
      titleAr: 'ابقَ على اطلاع بعلوم التربة',
      descriptionEn: 'Subscribe to our newsletter for the latest research, events, and news from the Syrian Soil Science Society.',
      descriptionAr: 'اشترك في نشرتنا الإخبارية للحصول على أحدث الأبحاث والفعاليات والأخبار من جمعية علوم التربة السورية.',
      buttonLabelEn: 'Subscribe',
      buttonLabelAr: 'اشترك',
      placeholderEn: 'Enter your email address',
      placeholderAr: 'أدخل عنوان بريدك الإلكتروني',
      bgColor: 'bg-forest',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-16' },
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    nameAr: 'نموذج الاتصال',
    description: 'Full contact form with validation',
    descriptionAr: 'نموذج اتصال كامل مع التحقق',
    componentType: 'contact-form',
    category: 'Forms',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Get In Touch',
      titleAr: 'تواصل معنا',
      submitButtonLabelEn: 'Send Message',
      submitButtonLabelAr: 'إرسال الرسالة',
    },
    defaultStyling: { bgColor: 'bg-soil-sand/10', paddingClass: 'py-16' },
  },
  // ── Dynamic ───────────────────────────────────────────────────────────────
  {
    id: 'latest-news-feed',
    name: 'Latest News Feed',
    nameAr: 'آخر الأخبار',
    description: 'Dynamic feed of latest published news articles',
    descriptionAr: 'تغذية ديناميكية بأحدث المقالات الإخبارية المنشورة',
    componentType: 'latest-news-feed',
    category: 'Dynamic',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Latest News',
      titleAr: 'آخر الأخبار',
      count: 3,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'upcoming-events-feed',
    name: 'Upcoming Events',
    nameAr: 'الفعاليات القادمة',
    description: 'Dynamic feed of upcoming events',
    descriptionAr: 'تغذية ديناميكية بالفعاليات القادمة',
    componentType: 'upcoming-events-feed',
    category: 'Dynamic',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Upcoming Events',
      titleAr: 'الفعاليات القادمة',
      count: 3,
    },
    defaultStyling: { bgColor: 'bg-soil-sand/20', paddingClass: 'py-16' },
  },
  // ── Custom ────────────────────────────────────────────────────────────────
  {
    id: 'custom-blank',
    name: 'Custom Section',
    nameAr: 'قسم مخصص',
    description: 'Start from blank — build with content blocks (heading, image, button, etc.)',
    descriptionAr: 'ابدأ من الفراغ — ابنِ بكتل المحتوى (عنوان، صورة، زر، إلخ)',
    componentType: 'custom',
    category: 'Custom',
    defaultData: { blocks: [] },
    defaultConfig: {
      titleEn: '',
      titleAr: '',
      bgColor: 'bg-white',
    },
    defaultStyling: { paddingClass: 'py-16' },
  },

  // ── Features ──────────────────────────────────────────────────────────────
  {
    id: 'features-grid',
    name: 'Features Grid',
    nameAr: 'شبكة الميزات',
    description: 'Icon-led feature grid with title and description per feature',
    descriptionAr: 'شبكة ميزات بأيقونات مع عنوان ووصف لكل ميزة',
    componentType: 'features-grid',
    category: 'Features',
    defaultData: {
      items: [
        { icon: '⚡', titleEn: 'Lightning Fast', titleAr: 'سريع البرق', descriptionEn: 'Optimised for peak performance across all devices and network conditions.', descriptionAr: 'مُحسَّن لأقصى أداء على جميع الأجهزة وظروف الشبكة.' },
        { icon: '🔒', titleEn: 'Secure by Default', titleAr: 'آمن افتراضياً', descriptionEn: 'Enterprise-grade security built into every layer of the platform.', descriptionAr: 'أمان على مستوى المؤسسات مدمج في كل طبقة من طبقات المنصة.' },
        { icon: '🌐', titleEn: 'Global Reach', titleAr: 'انتشار عالمي', descriptionEn: 'Deliver content worldwide with our distributed edge network.', descriptionAr: 'وصّل المحتوى في جميع أنحاء العالم عبر شبكتنا الموزعة.' },
        { icon: '📊', titleEn: 'Rich Analytics', titleAr: 'تحليلات غنية', descriptionEn: 'Gain actionable insights with real-time dashboards and reports.', descriptionAr: 'احصل على رؤى قابلة للتنفيذ عبر لوحات معلومات وتقارير فورية.' },
        { icon: '🔄', titleEn: 'Seamless Sync', titleAr: 'مزامنة سلسة', descriptionEn: 'Keep all your data in sync automatically across every device.', descriptionAr: 'احتفظ بجميع بياناتك متزامنة تلقائياً عبر كل جهاز.' },
        { icon: '🛠️', titleEn: 'Easy Customisation', titleAr: 'تخصيص سهل', descriptionEn: 'Adapt every detail to match your brand without writing code.', descriptionAr: 'كيّف كل تفصيلة لتتناسب مع علامتك التجارية دون كتابة كود.' },
      ],
    },
    defaultConfig: {
      titleEn: 'Everything You Need to Succeed',
      titleAr: 'كل ما تحتاجه للنجاح',
      subtitleEn: 'A complete toolkit designed for modern teams',
      subtitleAr: 'مجموعة أدوات متكاملة مصممة للفرق الحديثة',
      columns: 3,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-20' },
  },
  {
    id: 'features-alternating',
    name: 'Alternating Features',
    nameAr: 'ميزات متناوبة',
    description: 'Two-column alternating image + text rows for deep feature storytelling',
    descriptionAr: 'صفوف متناوبة من صورة ونص لعمودين لسرد قصة الميزات',
    componentType: 'features-alternating',
    category: 'Features',
    defaultData: {
      items: [
        { icon: '🎯', titleEn: 'Precision Targeting', titleAr: 'استهداف دقيق', descriptionEn: 'Reach the right audience at the right time with intelligent segmentation tools.', descriptionAr: 'اصل إلى الجمهور المناسب في الوقت المناسب بأدوات التجزئة الذكية.', image: '' },
        { icon: '🤖', titleEn: 'AI-Powered Automation', titleAr: 'أتمتة مدعومة بالذكاء الاصطناعي', descriptionEn: 'Let smart automation handle repetitive tasks so your team can focus on strategy.', descriptionAr: 'دع الأتمتة الذكية تتولى المهام المتكررة حتى يتفرغ فريقك للاستراتيجية.', image: '' },
        { icon: '📱', titleEn: 'Mobile-First Design', titleAr: 'تصميم يُقدّم الجوال أولاً', descriptionEn: 'Every experience is crafted for mobile users first, then scaled beautifully to desktop.', descriptionAr: 'كل تجربة مصممة لمستخدمي الجوال أولاً ثم تتوسع بشكل جميل للحاسوب.', image: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Built for the Way You Work',
      titleAr: 'مبني لطريقة عملك',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-20' },
  },
  {
    id: 'features-highlight',
    name: 'Feature Highlight',
    nameAr: 'تمييز الميزة',
    description: 'Single large feature spotlight with image, bullets and CTA',
    descriptionAr: 'تسليط الضوء على ميزة رئيسية واحدة مع صورة ونقاط وزر إجراء',
    componentType: 'feature-highlight',
    category: 'Features',
    defaultData: {
      bullets: [
        { textEn: 'Fully customisable with zero code required', textAr: 'قابل للتخصيص الكامل دون الحاجة إلى كود' },
        { textEn: 'Works with all major third-party integrations', textAr: 'يعمل مع جميع التكاملات الرئيسية مع أطراف ثالثة' },
        { textEn: 'Backed by 99.99% uptime SLA guarantee', textAr: 'مدعوم بضمان اتفاقية مستوى الخدمة بوقت تشغيل 99.99%' },
      ],
    },
    defaultConfig: {
      titleEn: 'The Smarter Way to Manage Your Platform',
      titleAr: 'الطريقة الأذكى لإدارة منصتك',
      descriptionEn: 'Unlock the full potential of your workflow with our intuitive management suite — designed for teams of every size.',
      descriptionAr: 'أطلق الإمكانات الكاملة لسير عملك باستخدام مجموعة الإدارة البديهية لدينا — مصممة للفرق من جميع الأحجام.',
      ctaLabelEn: 'See All Features',
      ctaLabelAr: 'شاهد جميع الميزات',
      ctaUrl: '/features',
      image: '',
      imagePosition: 'right',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-20' },
  },

  // ── Blog ─────────────────────────────────────────────────────────────────
  {
    id: 'blog-grid',
    name: 'Blog Post Grid',
    nameAr: 'شبكة مقالات المدونة',
    description: 'Three-column grid of blog post cards with thumbnail, category and date',
    descriptionAr: 'شبكة ثلاثية الأعمدة لبطاقات مقالات المدونة مع صورة مصغرة وتصنيف وتاريخ',
    componentType: 'blog-grid',
    category: 'Blog',
    defaultData: {
      posts: [
        { titleEn: '10 Trends Shaping the Industry in 2025', titleAr: '10 اتجاهات تشكّل الصناعة في 2025', categoryEn: 'Industry', categoryAr: 'الصناعة', date: '2025-01-15', excerpt: 'A deep dive into the forces transforming how teams work and deliver value this year.', image: '', slug: '/blog/trends-2025' },
        { titleEn: 'How to Build a High-Performance Team', titleAr: 'كيف تبني فريق عالي الأداء', categoryEn: 'Leadership', categoryAr: 'القيادة', date: '2025-01-08', excerpt: 'The frameworks and habits shared by the world\'s most productive teams.', image: '', slug: '/blog/high-performance-team' },
        { titleEn: 'The Future of Remote Collaboration', titleAr: 'مستقبل التعاون عن بُعد', categoryEn: 'Remote Work', categoryAr: 'العمل عن بُعد', date: '2024-12-29', excerpt: 'Emerging tools and strategies that are redefining distributed team dynamics.', image: '', slug: '/blog/remote-collaboration' },
      ],
    },
    defaultConfig: {
      titleEn: 'From Our Blog',
      titleAr: 'من مدونتنا',
      viewAllLabelEn: 'View All Posts',
      viewAllLabelAr: 'عرض جميع المقالات',
      viewAllUrl: '/blog',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'blog-featured',
    name: 'Featured Article',
    nameAr: 'مقالة مميزة',
    description: 'Large hero-style featured article with sidebar list of recent posts',
    descriptionAr: 'مقالة مميزة بأسلوب بانر كبير مع قائمة جانبية للمقالات الأخيرة',
    componentType: 'blog-featured',
    category: 'Blog',
    defaultData: {
      featured: {
        titleEn: 'A Complete Guide to Modern Product Strategy',
        titleAr: 'دليل شامل لاستراتيجية المنتج الحديثة',
        excerptEn: 'Learn how leading product teams prioritise, plan and ship features that customers love — and how to apply their methods to your own roadmap.',
        excerptAr: 'تعرّف على كيفية تحديد أولويات فرق المنتج الرائدة وتخطيط وشحن الميزات التي يحبها العملاء.',
        image: '',
        date: '2025-01-20',
        categoryEn: 'Product',
        categoryAr: 'المنتج',
        slug: '/blog/product-strategy-guide',
      },
      recent: [
        { titleEn: 'UX Writing: The Invisible Design Element', titleAr: 'كتابة تجربة المستخدم: عنصر التصميم غير المرئي', date: '2025-01-10', slug: '/blog/ux-writing' },
        { titleEn: 'API-First Development Explained', titleAr: 'شرح التطوير القائم على API أولاً', date: '2025-01-05', slug: '/blog/api-first' },
        { titleEn: 'Building Trust Through Transparency', titleAr: 'بناء الثقة من خلال الشفافية', date: '2024-12-28', slug: '/blog/trust-transparency' },
      ],
    },
    defaultConfig: {
      titleEn: 'Latest Insights',
      titleAr: 'أحدث الرؤى',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Portfolio ─────────────────────────────────────────────────────────────
  {
    id: 'portfolio-masonry',
    name: 'Portfolio Masonry',
    nameAr: 'معرض الأعمال المتداخل',
    description: 'Filterable masonry grid portfolio with category tags',
    descriptionAr: 'شبكة معرض أعمال قابلة للتصفية مع علامات التصنيف',
    componentType: 'portfolio-masonry',
    category: 'Portfolio',
    defaultData: {
      items: [
        { titleEn: 'Brand Identity Redesign', titleAr: 'إعادة تصميم الهوية التجارية', categoryEn: 'Branding', categoryAr: 'العلامة التجارية', image: '', slug: '/portfolio/brand-redesign' },
        { titleEn: 'E-Commerce Platform', titleAr: 'منصة التجارة الإلكترونية', categoryEn: 'Web', categoryAr: 'الويب', image: '', slug: '/portfolio/ecommerce' },
        { titleEn: 'Mobile Banking App', titleAr: 'تطبيق الخدمات المصرفية المحمولة', categoryEn: 'Mobile', categoryAr: 'الجوال', image: '', slug: '/portfolio/banking-app' },
        { titleEn: 'Data Visualisation Dashboard', titleAr: 'لوحة تصور البيانات', categoryEn: 'Web', categoryAr: 'الويب', image: '', slug: '/portfolio/dashboard' },
        { titleEn: 'Corporate Annual Report', titleAr: 'التقرير السنوي للشركة', categoryEn: 'Print', categoryAr: 'المطبوعات', image: '', slug: '/portfolio/annual-report' },
        { titleEn: 'Augmented Reality Experience', titleAr: 'تجربة الواقع المعزز', categoryEn: 'Interactive', categoryAr: 'تفاعلي', image: '', slug: '/portfolio/ar-experience' },
      ],
      filters: ['All', 'Branding', 'Web', 'Mobile', 'Print', 'Interactive'],
    },
    defaultConfig: {
      titleEn: 'Our Work',
      titleAr: 'أعمالنا',
      subtitleEn: 'A selection of projects we are proud of',
      subtitleAr: 'مجموعة مختارة من المشاريع التي نفخر بها',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'portfolio-case-study',
    name: 'Case Study Cards',
    nameAr: 'بطاقات دراسة الحالة',
    description: 'Horizontal case study cards with result metrics and client info',
    descriptionAr: 'بطاقات دراسة الحالة الأفقية مع مقاييس النتائج ومعلومات العميل',
    componentType: 'case-study-cards',
    category: 'Portfolio',
    defaultData: {
      items: [
        {
          clientEn: 'Global Logistics Co.', clientAr: 'شركة اللوجستيات العالمية',
          titleEn: 'Reduced delivery time by 40%', titleAr: 'تقليل وقت التسليم بنسبة 40%',
          descriptionEn: 'We redesigned their supply chain visibility platform from the ground up, resulting in dramatic efficiency gains.', descriptionAr: 'أعدنا تصميم منصة رؤية سلسلة التوريد الخاصة بهم من الصفر، مما أسفر عن مكاسب جوهرية في الكفاءة.',
          metrics: [{ labelEn: 'Faster Delivery', labelAr: 'توصيل أسرع', value: '40%' }, { labelEn: 'Cost Saving', labelAr: 'توفير في التكاليف', value: '$2M' }],
          image: '', slug: '/portfolio/logistics',
        },
        {
          clientEn: 'FinTech Startup', clientAr: 'شركة فين-تك ناشئة',
          titleEn: '3× user retention after UX overhaul', titleAr: '3× زيادة الاحتفاظ بالمستخدمين بعد مراجعة UX',
          descriptionEn: 'A complete user experience redesign that transformed onboarding and daily engagement metrics.', descriptionAr: 'إعادة تصميم كاملة لتجربة المستخدم غيّرت معايير الإعداد والتفاعل اليومي.',
          metrics: [{ labelEn: 'Retention', labelAr: 'الاحتفاظ', value: '3×' }, { labelEn: 'NPS Score', labelAr: 'درجة NPS', value: '+68' }],
          image: '', slug: '/portfolio/fintech',
        },
      ],
    },
    defaultConfig: {
      titleEn: 'Client Success Stories',
      titleAr: 'قصص نجاح العملاء',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Pricing ───────────────────────────────────────────────────────────────
  {
    id: 'pricing-cards',
    name: 'Pricing Cards',
    nameAr: 'بطاقات الأسعار',
    description: 'Three-tier pricing cards with feature lists and CTA buttons',
    descriptionAr: 'بطاقات أسعار ثلاثية المستويات مع قوائم الميزات وأزرار الإجراءات',
    componentType: 'pricing-cards',
    category: 'Pricing',
    defaultData: {
      plans: [
        {
          nameEn: 'Starter', nameAr: 'المبتدئ',
          price: '$9', period: '/mo',
          descriptionEn: 'Perfect for individuals and small projects.', descriptionAr: 'مثالي للأفراد والمشاريع الصغيرة.',
          featuresEn: ['Up to 5 projects', '2 GB storage', 'Email support', 'Basic analytics'],
          featuresAr: ['حتى 5 مشاريع', '2 جيجابايت تخزين', 'دعم البريد الإلكتروني', 'تحليلات أساسية'],
          ctaLabelEn: 'Get Started', ctaLabelAr: 'ابدأ الآن', ctaUrl: '/signup', highlighted: false,
        },
        {
          nameEn: 'Professional', nameAr: 'الاحترافي',
          price: '$39', period: '/mo',
          descriptionEn: 'For growing teams that need more power.', descriptionAr: 'للفرق المتنامية التي تحتاج إلى مزيد من القوة.',
          featuresEn: ['Unlimited projects', '50 GB storage', 'Priority support', 'Advanced analytics', 'API access'],
          featuresAr: ['مشاريع غير محدودة', '50 جيجابايت تخزين', 'دعم ذو أولوية', 'تحليلات متقدمة', 'وصول API'],
          ctaLabelEn: 'Start Free Trial', ctaLabelAr: 'ابدأ التجربة المجانية', ctaUrl: '/signup?plan=pro', highlighted: true,
        },
        {
          nameEn: 'Enterprise', nameAr: 'المؤسسات',
          price: 'Custom', period: '',
          descriptionEn: 'Tailored solutions for large organisations.', descriptionAr: 'حلول مخصصة للمنظمات الكبيرة.',
          featuresEn: ['Everything in Pro', 'Dedicated infrastructure', 'SLA guarantee', 'Custom integrations', 'Onboarding support'],
          featuresAr: ['كل شيء في الاحترافي', 'بنية تحتية مخصصة', 'ضمان اتفاقية الخدمة', 'تكاملات مخصصة', 'دعم الإعداد'],
          ctaLabelEn: 'Contact Sales', ctaLabelAr: 'تواصل مع المبيعات', ctaUrl: '/contact', highlighted: false,
        },
      ],
    },
    defaultConfig: {
      titleEn: 'Simple, Transparent Pricing',
      titleAr: 'أسعار بسيطة وشفافة',
      subtitleEn: 'No hidden fees. Cancel anytime.',
      subtitleAr: 'لا رسوم مخفية. إلغاء في أي وقت.',
      annualDiscountEn: 'Save 20% with annual billing',
      annualDiscountAr: 'وفّر 20% مع الفوترة السنوية',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-20' },
  },
  {
    id: 'pricing-comparison',
    name: 'Pricing Comparison Table',
    nameAr: 'جدول مقارنة الأسعار',
    description: 'Detailed feature comparison table across pricing tiers',
    descriptionAr: 'جدول مقارنة تفصيلي للميزات عبر مستويات الأسعار',
    componentType: 'pricing-table',
    category: 'Pricing',
    defaultData: {
      tiers: ['Starter', 'Pro', 'Enterprise'],
      rows: [
        { featureEn: 'Projects', featureAr: 'المشاريع', values: ['5', 'Unlimited', 'Unlimited'] },
        { featureEn: 'Storage', featureAr: 'التخزين', values: ['2 GB', '50 GB', 'Custom'] },
        { featureEn: 'API Access', featureAr: 'الوصول إلى API', values: [false, true, true] },
        { featureEn: 'Custom Domain', featureAr: 'نطاق مخصص', values: [false, true, true] },
        { featureEn: 'SLA Guarantee', featureAr: 'ضمان اتفاقية الخدمة', values: [false, false, true] },
        { featureEn: 'Dedicated Support', featureAr: 'دعم مخصص', values: [false, false, true] },
      ],
    },
    defaultConfig: {
      titleEn: 'Compare Plans',
      titleAr: 'قارن الخطط',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── Testimonials ──────────────────────────────────────────────────────────
  {
    id: 'testimonials-carousel',
    name: 'Testimonials Carousel',
    nameAr: 'كاروسيل الشهادات',
    description: 'Full-width rotating testimonial slider with star ratings',
    descriptionAr: 'شريط شهادات دوّار كامل العرض مع تقييمات النجوم',
    componentType: 'testimonials-carousel',
    category: 'Testimonials',
    defaultData: {
      items: [
        { nameEn: 'Sarah Mitchell', nameAr: 'سارة ميتشل', roleEn: 'CEO, Apex Solutions', roleAr: 'الرئيس التنفيذي، شركة Apex Solutions', quoteEn: 'This platform completely transformed how our team collaborates. We cut project overhead by 35% in the first month.', quoteAr: 'غيّرت هذه المنصة بشكل كامل طريقة تعاون فريقنا. قللنا التكاليف العامة للمشروع بنسبة 35% في الشهر الأول.', rating: 5, avatar: '' },
        { nameEn: 'James Okafor', nameAr: 'جيمس أوكافور', roleEn: 'Head of Product, NovaTech', roleAr: 'رئيس المنتج، NovaTech', quoteEn: 'The onboarding was seamless and the support team is incredibly responsive. Highly recommended.', quoteAr: 'كان الإعداد سلساً وفريق الدعم سريع الاستجابة بشكل لا يصدق. أوصي به بشدة.', rating: 5, avatar: '' },
        { nameEn: 'Priya Sharma', nameAr: 'بريا شارما', roleEn: 'Marketing Director, BrightEdge', roleAr: 'مديرة التسويق، BrightEdge', quoteEn: 'We tried five other tools before this one. Nothing comes close to the depth of features at this price point.', quoteAr: 'جربنا خمس أدوات أخرى قبل هذه. لا شيء يقترب من عمق الميزات بهذا السعر.', rating: 5, avatar: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Trusted by Thousands of Teams',
      titleAr: 'موثوق به من آلاف الفرق',
      autoplay: true,
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-20' },
  },
  {
    id: 'testimonials-wall',
    name: 'Testimonial Wall',
    nameAr: 'جدار الشهادات',
    description: 'Masonry-style testimonial wall with multiple quote cards',
    descriptionAr: 'جدار شهادات بأسلوب المتداخل مع بطاقات اقتباس متعددة',
    componentType: 'testimonials-wall',
    category: 'Testimonials',
    defaultData: {
      items: [
        { nameEn: 'Alex Turner', nameAr: 'أليكس تيرنر', roleEn: 'Freelance Developer', roleAr: 'مطور مستقل', quoteEn: 'Saved me hours every week. The automation features alone are worth the subscription.', quoteAr: 'وفّر لي ساعات كل أسبوع. ميزات الأتمتة وحدها تستحق الاشتراك.', rating: 5, avatar: '' },
        { nameEn: 'Maria González', nameAr: 'ماريا غونزاليس', roleEn: 'UX Designer, Studio M', roleAr: 'مصممة UX، Studio M', quoteEn: 'Clean interface, powerful tools. My clients love the reports it generates.', quoteAr: 'واجهة نظيفة وأدوات قوية. عملائي يحبون التقارير التي تولّدها.', rating: 4, avatar: '' },
        { nameEn: 'David Chen', nameAr: 'ديفيد تشين', roleEn: 'CTO, ScaleUp', roleAr: 'المدير التقني، ScaleUp', quoteEn: 'We integrated it into our stack in under a day. Robust API and great documentation.', quoteAr: 'دمجناها في بنيتنا التحتية في أقل من يوم. API قوي وتوثيق ممتاز.', rating: 5, avatar: '' },
        { nameEn: 'Emma Johansson', nameAr: 'إيما يوهانسون', roleEn: 'Operations Manager', roleAr: 'مدير العمليات', quoteEn: 'The reporting dashboards give me complete visibility into every project at a glance.', quoteAr: 'لوحات التقارير تمنحني رؤية كاملة لكل مشروع في لمحة واحدة.', rating: 5, avatar: '' },
        { nameEn: 'Kevin Adeyemi', nameAr: 'كيفن أديمي', roleEn: 'Startup Founder', roleAr: 'مؤسس شركة ناشئة', quoteEn: 'Scaled from 3 to 30 team members without ever outgrowing the platform.', quoteAr: 'توسعنا من 3 إلى 30 عضواً في الفريق دون أن نتجاوز المنصة أبداً.', rating: 5, avatar: '' },
        { nameEn: 'Lisa Park', nameAr: 'ليزا بارك', roleEn: 'Product Manager, Lens', roleAr: 'مديرة المنتج، Lens', quoteEn: 'Customer support is exceptional — they respond within minutes, not days.', quoteAr: 'دعم العملاء استثنائي — يردون في دقائق وليس أياماً.', rating: 5, avatar: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'What People Are Saying',
      titleAr: 'ما يقوله الناس',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── Team ──────────────────────────────────────────────────────────────────
  {
    id: 'team-leadership',
    name: 'Leadership Team',
    nameAr: 'فريق القيادة',
    description: 'Large portrait cards for executive and leadership team profiles',
    descriptionAr: 'بطاقات صور كبيرة لملفات الفريق التنفيذي والقيادي',
    componentType: 'team-leadership',
    category: 'Team',
    defaultData: {
      members: [
        { nameEn: 'Alexandra Reed', nameAr: 'ألكساندرا ريد', titleEn: 'Chief Executive Officer', titleAr: 'الرئيس التنفيذي', bioEn: 'Over 20 years building category-defining products and leading high-performance teams.', bioAr: 'أكثر من 20 عاماً في بناء منتجات تحدد الفئة وقيادة فرق عالية الأداء.', photo: '', linkedIn: '', twitter: '' },
        { nameEn: 'Michael Torres', nameAr: 'مايكل توريس', titleEn: 'Chief Technology Officer', titleAr: 'المدير التقني', bioEn: 'Former principal engineer at leading tech companies, passionate about scalable architecture.', bioAr: 'مهندس رئيسي سابق في شركات تقنية رائدة، شغوف بالبنية المعمارية القابلة للتطوير.', photo: '', linkedIn: '', twitter: '' },
        { nameEn: 'Yuki Tanaka', nameAr: 'يوكي تاناكا', titleEn: 'Chief Design Officer', titleAr: 'مدير التصميم الرئيسي', bioEn: 'Award-winning designer with a focus on human-centred experiences that drive outcomes.', bioAr: 'مصمم حائز على جوائز يركز على التجارب المتمحورة حول الإنسان التي تحقق النتائج.', photo: '', linkedIn: '', twitter: '' },
        { nameEn: 'Fatima Al-Amin', nameAr: 'فاطمة الأمين', titleEn: 'Chief Operating Officer', titleAr: 'المدير التشغيلي الرئيسي', bioEn: 'Operations leader who has scaled businesses from seed to Series C across three continents.', bioAr: 'قائدة عمليات نجحت في توسيع نطاق الأعمال من المرحلة الأولى إلى الجولة C عبر ثلاث قارات.', photo: '', linkedIn: '', twitter: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Meet the Leadership',
      titleAr: 'تعرّف على القيادة',
      subtitleEn: 'Experienced operators united by a common mission',
      subtitleAr: 'مشغّلون ذوو خبرة توحّدهم رسالة مشتركة',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-20' },
  },
  {
    id: 'team-compact',
    name: 'Team Compact List',
    nameAr: 'قائمة الفريق المدمجة',
    description: 'Compact horizontal list of team members with avatars and roles',
    descriptionAr: 'قائمة أفقية مدمجة لأعضاء الفريق مع الصور الرمزية والأدوار',
    componentType: 'team-compact',
    category: 'Team',
    defaultData: {
      members: [
        { nameEn: 'Chris Webb', nameAr: 'كريس ويب', roleEn: 'Engineering Lead', roleAr: 'قائد الهندسة', photo: '' },
        { nameEn: 'Amara Diallo', nameAr: 'أمارا ديالو', roleEn: 'Product Manager', roleAr: 'مدير المنتج', photo: '' },
        { nameEn: 'Ryu Nakamura', nameAr: 'ريو ناكامورا', roleEn: 'Head of Design', roleAr: 'رئيس التصميم', photo: '' },
        { nameEn: 'Isabel Costa', nameAr: 'إيزابيل كوستا', roleEn: 'Marketing Manager', roleAr: 'مدير التسويق', photo: '' },
        { nameEn: 'Tobias Klein', nameAr: 'توبياس كلاين', roleEn: 'Data Scientist', roleAr: 'عالم بيانات', photo: '' },
        { nameEn: 'Nadia Hassan', nameAr: 'نادية حسن', roleEn: 'Customer Success', roleAr: 'نجاح العملاء', photo: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'The People Behind the Platform',
      titleAr: 'الأشخاص خلف المنصة',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Gallery ───────────────────────────────────────────────────────────────
  {
    id: 'gallery-grid',
    name: 'Photo Gallery Grid',
    nameAr: 'شبكة معرض الصور',
    description: 'Responsive masonry photo gallery with lightbox support',
    descriptionAr: 'معرض صور متجاوب بأسلوب المتداخل مع دعم العرض الموسّع',
    componentType: 'gallery-grid',
    category: 'Gallery',
    defaultData: {
      images: [
        { src: '', altEn: 'Gallery image 1', altAr: 'صورة المعرض 1', captionEn: '', captionAr: '' },
        { src: '', altEn: 'Gallery image 2', altAr: 'صورة المعرض 2', captionEn: '', captionAr: '' },
        { src: '', altEn: 'Gallery image 3', altAr: 'صورة المعرض 3', captionEn: '', captionAr: '' },
        { src: '', altEn: 'Gallery image 4', altAr: 'صورة المعرض 4', captionEn: '', captionAr: '' },
        { src: '', altEn: 'Gallery image 5', altAr: 'صورة المعرض 5', captionEn: '', captionAr: '' },
        { src: '', altEn: 'Gallery image 6', altAr: 'صورة المعرض 6', captionEn: '', captionAr: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Photo Gallery',
      titleAr: 'معرض الصور',
      columns: 3,
      lightbox: true,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'gallery-slider',
    name: 'Image Slider',
    nameAr: 'شريط الصور',
    description: 'Full-width touch-enabled image slider with captions',
    descriptionAr: 'شريط صور كامل العرض قابل للمس مع تسميات توضيحية',
    componentType: 'image-slider',
    category: 'Gallery',
    defaultData: {
      slides: [
        { src: '', captionEn: 'Our state-of-the-art headquarters', captionAr: 'مقر شركتنا المتطور', altEn: 'Headquarters', altAr: 'المقر الرئيسي' },
        { src: '', captionEn: 'The annual all-hands meeting', captionAr: 'الاجتماع السنوي الشامل', altEn: 'All-hands meeting', altAr: 'اجتماع شامل' },
        { src: '', captionEn: 'Our global team at work', captionAr: 'فريقنا العالمي في العمل', altEn: 'Team at work', altAr: 'الفريق في العمل' },
      ],
    },
    defaultConfig: {
      titleEn: 'Life at Our Company',
      titleAr: 'الحياة في شركتنا',
      autoplay: true,
      interval: 5000,
    },
    defaultStyling: { bgColor: 'bg-gray-900', paddingClass: 'py-0' },
  },

  // ── Video ─────────────────────────────────────────────────────────────────
  {
    id: 'video-hero',
    name: 'Video Hero',
    nameAr: 'بانر فيديو رئيسي',
    description: 'Full-width video background hero with overlay text',
    descriptionAr: 'بانر رئيسي بخلفية فيديو كاملة العرض مع نص متراكب',
    componentType: 'video-hero',
    category: 'Video',
    defaultData: {},
    defaultConfig: {
      titleEn: 'A Story Worth Telling',
      titleAr: 'قصة تستحق أن تُروى',
      subtitleEn: 'See how we are changing the way the world works',
      subtitleAr: 'شاهد كيف نغيّر الطريقة التي يعمل بها العالم',
      videoUrl: '',
      posterImage: '',
      ctaLabelEn: 'Watch the Film',
      ctaLabelAr: 'شاهد الفيلم',
      ctaUrl: '#',
      overlayOpacity: 0.5,
    },
    defaultStyling: { paddingClass: 'py-40' },
  },
  {
    id: 'video-embed',
    name: 'Video Embed Section',
    nameAr: 'قسم تضمين الفيديو',
    description: 'Centred video embed with title, description and optional transcript',
    descriptionAr: 'تضمين فيديو مركزي مع عنوان ووصف ونص اختياري',
    componentType: 'video-embed',
    category: 'Video',
    defaultData: {},
    defaultConfig: {
      titleEn: 'See It In Action',
      titleAr: 'شاهده في العمل',
      descriptionEn: 'Watch our 3-minute product overview and discover how teams like yours are achieving more.',
      descriptionAr: 'شاهد نظرة عامة على منتجنا لمدة 3 دقائق واكتشف كيف تحقق فرق مثل فريقك المزيد.',
      videoUrl: '',
      aspectRatio: '16/9',
      showTranscript: false,
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Steps ─────────────────────────────────────────────────────────────────
  {
    id: 'steps-horizontal',
    name: 'How It Works (Steps)',
    nameAr: 'كيف يعمل (خطوات)',
    description: 'Numbered horizontal step-by-step process section',
    descriptionAr: 'قسم عملية خطوة بخطوة أفقي مرقّم',
    componentType: 'steps-horizontal',
    category: 'Steps',
    defaultData: {
      steps: [
        { number: '01', titleEn: 'Sign Up in Seconds', titleAr: 'سجّل في ثوانٍ', descriptionEn: 'Create your account with just an email — no credit card required to start.', descriptionAr: 'أنشئ حسابك ببريد إلكتروني فقط — لا بطاقة ائتمان مطلوبة للبدء.' },
        { number: '02', titleEn: 'Set Up Your Workspace', titleAr: 'أعدّ مساحة عملك', descriptionEn: 'Invite your team, import your data and configure your workflow in minutes.', descriptionAr: 'ادعُ فريقك واستورد بياناتك وهيّئ سير عملك في دقائق.' },
        { number: '03', titleEn: 'Launch and Track', titleAr: 'أطلق وتتبّع', descriptionEn: 'Go live and monitor performance with real-time dashboards built into every view.', descriptionAr: 'انطلق وراقب الأداء بلوحات معلومات فورية مدمجة في كل عرض.' },
        { number: '04', titleEn: 'Scale with Confidence', titleAr: 'توسّع بثقة', descriptionEn: 'As your needs grow, our platform scales seamlessly — no migrations, no downtime.', descriptionAr: 'مع نمو احتياجاتك، تتوسع منصتنا بسلاسة — بلا ترحيل ولا انقطاع.' },
      ],
    },
    defaultConfig: {
      titleEn: 'How It Works',
      titleAr: 'كيف يعمل',
      subtitleEn: 'Up and running in less than 10 minutes',
      subtitleAr: 'جاهز للعمل في أقل من 10 دقائق',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-20' },
  },
  {
    id: 'steps-vertical',
    name: 'Process Timeline (Vertical)',
    nameAr: 'جدول زمني للعملية (رأسي)',
    description: 'Vertical numbered process steps with icons and connectors',
    descriptionAr: 'خطوات عملية رأسية مرقّمة مع أيقونات وروابط',
    componentType: 'steps-vertical',
    category: 'Steps',
    defaultData: {
      steps: [
        { icon: '📋', titleEn: 'Discovery & Research', titleAr: 'الاستكشاف والبحث', descriptionEn: 'We begin by deeply understanding your goals, audience and competitive landscape through structured interviews and data analysis.', descriptionAr: 'نبدأ بفهم عميق لأهدافك وجمهورك والمشهد التنافسي من خلال مقابلات منظمة وتحليل البيانات.' },
        { icon: '✏️', titleEn: 'Strategy & Design', titleAr: 'الاستراتيجية والتصميم', descriptionEn: 'Our team crafts a tailored strategy and translates it into detailed designs and interactive prototypes.', descriptionAr: 'يضع فريقنا استراتيجية مخصصة ويترجمها إلى تصاميم مفصّلة ونماذج أولية تفاعلية.' },
        { icon: '🔧', titleEn: 'Build & Iterate', titleAr: 'البناء والتكرار', descriptionEn: 'We build in agile sprints, continuously testing and refining based on real user feedback.', descriptionAr: 'نبني في سباقات رشيقة، ونختبر باستمرار ونحسّن بناءً على تغذية راجعة حقيقية من المستخدمين.' },
        { icon: '🚀', titleEn: 'Launch & Optimise', titleAr: 'الإطلاق والتحسين', descriptionEn: 'We manage the full launch process and continue to optimise performance post-release.', descriptionAr: 'ندير عملية الإطلاق الكاملة ونستمر في تحسين الأداء بعد الإصدار.' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Process',
      titleAr: 'عمليتنا',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Logos ─────────────────────────────────────────────────────────────────
  {
    id: 'logos-partners',
    name: 'Partner Logos',
    nameAr: 'شعارات الشركاء',
    description: 'Grayscale partner and client logo strip with hover colour effect',
    descriptionAr: 'شريط شعارات الشركاء والعملاء بالتدرج الرمادي مع تأثير اللون عند التحويم',
    componentType: 'logos-strip',
    category: 'Logos',
    defaultData: {
      logos: [
        { nameEn: 'Partner One', nameAr: 'الشريك الأول', src: '', url: '' },
        { nameEn: 'Partner Two', nameAr: 'الشريك الثاني', src: '', url: '' },
        { nameEn: 'Partner Three', nameAr: 'الشريك الثالث', src: '', url: '' },
        { nameEn: 'Partner Four', nameAr: 'الشريك الرابع', src: '', url: '' },
        { nameEn: 'Partner Five', nameAr: 'الشريك الخامس', src: '', url: '' },
        { nameEn: 'Partner Six', nameAr: 'الشريك السادس', src: '', url: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Trusted by Industry Leaders',
      titleAr: 'موثوق به من قبل رواد الصناعة',
      grayscale: true,
      scrolling: false,
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-12' },
  },
  {
    id: 'logos-scrolling',
    name: 'Scrolling Logo Marquee',
    nameAr: 'شريط شعارات متحرك',
    description: 'Infinite auto-scrolling logo marquee for social proof',
    descriptionAr: 'شريط شعارات يتمرر تلقائياً بلا نهاية للدليل الاجتماعي',
    componentType: 'logos-marquee',
    category: 'Logos',
    defaultData: {
      logos: [
        { nameEn: 'Company A', nameAr: 'الشركة أ', src: '' },
        { nameEn: 'Company B', nameAr: 'الشركة ب', src: '' },
        { nameEn: 'Company C', nameAr: 'الشركة ج', src: '' },
        { nameEn: 'Company D', nameAr: 'الشركة د', src: '' },
        { nameEn: 'Company E', nameAr: 'الشركة هـ', src: '' },
        { nameEn: 'Company F', nameAr: 'الشركة و', src: '' },
        { nameEn: 'Company G', nameAr: 'الشركة ز', src: '' },
        { nameEn: 'Company H', nameAr: 'الشركة ح', src: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Powering Teams at Companies Like These',
      titleAr: 'يدعم الفرق في شركات مثل هذه',
      speed: 'normal',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-12' },
  },

  // ── Tabs ──────────────────────────────────────────────────────────────────
  {
    id: 'tabs-content',
    name: 'Tabbed Content',
    nameAr: 'محتوى بالتبويبات',
    description: 'Horizontal tab navigation with rich content panels',
    descriptionAr: 'تنقل بتبويبات أفقية مع لوحات محتوى غنية',
    componentType: 'tabs-content',
    category: 'Tabs',
    defaultData: {
      tabs: [
        {
          labelEn: 'For Businesses', labelAr: 'للشركات',
          titleEn: 'Scale Your Operations', titleAr: 'وسّع نطاق عملياتك',
          contentEn: 'Streamline workflows, unify data sources and give every team member the context they need to make better decisions faster.',
          contentAr: 'حسّن سير العمل، وحّد مصادر البيانات وامنح كل عضو في الفريق السياق الذي يحتاجه لاتخاذ قرارات أفضل وأسرع.',
          image: '',
        },
        {
          labelEn: 'For Developers', labelAr: 'للمطورين',
          titleEn: 'Build Without Limits', titleAr: 'ابنِ بلا حدود',
          contentEn: 'Leverage our full REST and GraphQL APIs, webhooks and SDKs to create bespoke integrations that fit perfectly into your existing stack.',
          contentAr: 'استفد من واجهات برمجة التطبيقات الكاملة REST و GraphQL والخطافات وحزم SDK لإنشاء تكاملات مخصصة تتناسب تماماً مع بنيتك الحالية.',
          image: '',
        },
        {
          labelEn: 'For Agencies', labelAr: 'للوكالات',
          titleEn: 'Deliver More for Clients', titleAr: 'قدّم أكثر للعملاء',
          contentEn: 'Manage multiple client accounts from a single dashboard with robust white-labelling and permissions that keep every project organised.',
          contentAr: 'أدر حسابات عملاء متعددة من لوحة تحكم واحدة مع تمييز بالعلامة البيضاء قوي وصلاحيات تبقي كل مشروع منظماً.',
          image: '',
        },
      ],
    },
    defaultConfig: {
      titleEn: 'Built for Every Team',
      titleAr: 'مبني لكل فريق',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── Comparison ────────────────────────────────────────────────────────────
  {
    id: 'comparison-before-after',
    name: 'Before & After Comparison',
    nameAr: 'مقارنة قبل وبعد',
    description: 'Side-by-side before/after slider or split view',
    descriptionAr: 'شريط مقارنة جنباً إلى جنب أو عرض منقسم قبل وبعد',
    componentType: 'comparison-slider',
    category: 'Comparison',
    defaultData: {
      beforeImage: '',
      afterImage: '',
      beforeLabelEn: 'Before',
      beforeLabelAr: 'قبل',
      afterLabelEn: 'After',
      afterLabelAr: 'بعد',
    },
    defaultConfig: {
      titleEn: 'See the Difference',
      titleAr: 'شاهد الفرق',
      descriptionEn: 'Drag the slider to compare results before and after using our solution.',
      descriptionAr: 'اسحب الشريط لمقارنة النتائج قبل وبعد استخدام حلنا.',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },
  {
    id: 'comparison-table',
    name: 'Competitor Comparison',
    nameAr: 'مقارنة المنافسين',
    description: 'Feature table comparing your product against competitors',
    descriptionAr: 'جدول ميزات يقارن منتجك مع المنافسين',
    componentType: 'competitor-comparison',
    category: 'Comparison',
    defaultData: {
      competitors: ['Us', 'Competitor A', 'Competitor B'],
      rows: [
        { featureEn: 'Unlimited Projects', featureAr: 'مشاريع غير محدودة', values: [true, false, false] },
        { featureEn: 'Real-time Collaboration', featureAr: 'تعاون فوري', values: [true, true, false] },
        { featureEn: 'Advanced Analytics', featureAr: 'تحليلات متقدمة', values: [true, false, true] },
        { featureEn: '24/7 Support', featureAr: 'دعم 24/7', values: [true, false, false] },
        { featureEn: 'API Access', featureAr: 'وصول API', values: [true, true, false] },
        { featureEn: 'Custom Integrations', featureAr: 'تكاملات مخصصة', values: [true, false, false] },
      ],
    },
    defaultConfig: {
      titleEn: 'Why Choose Us',
      titleAr: 'لماذا تختارنا',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── Maps ──────────────────────────────────────────────────────────────────
  {
    id: 'map-contact',
    name: 'Map & Location',
    nameAr: 'الخريطة والموقع',
    description: 'Embedded map with address, contact details and directions CTA',
    descriptionAr: 'خريطة مضمّنة مع العنوان وتفاصيل الاتصال وزر الاتجاهات',
    componentType: 'map-location',
    category: 'Maps',
    defaultData: {
      locations: [
        {
          nameEn: 'Main Office', nameAr: 'المكتب الرئيسي',
          addressEn: '123 Business Avenue, City, Country', addressAr: '123 شارع الأعمال، المدينة، البلد',
          phone: '+1 (555) 000-0000',
          email: 'hello@example.com',
          hours: 'Mon–Fri: 9am – 6pm',
          mapEmbedUrl: '',
          lat: 0, lng: 0,
        },
      ],
    },
    defaultConfig: {
      titleEn: 'Find Us',
      titleAr: 'اعثر علينا',
      ctaLabelEn: 'Get Directions',
      ctaLabelAr: 'احصل على الاتجاهات',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'map-offices',
    name: 'Global Offices Map',
    nameAr: 'خريطة المكاتب العالمية',
    description: 'Multiple office locations with map pins and contact info tabs',
    descriptionAr: 'مواقع مكاتب متعددة مع دبابيس الخريطة وتبويبات معلومات الاتصال',
    componentType: 'offices-map',
    category: 'Maps',
    defaultData: {
      offices: [
        { cityEn: 'New York', cityAr: 'نيويورك', addressEn: '350 Fifth Avenue, Suite 2400', addressAr: '350 الجادة الخامسة، جناح 2400', phone: '+1 212 000 0000', email: 'ny@example.com' },
        { cityEn: 'London', cityAr: 'لندن', addressEn: '1 Canada Square, Canary Wharf', addressAr: '1 ميدان كندا، كناري وارف', phone: '+44 20 0000 0000', email: 'london@example.com' },
        { cityEn: 'Dubai', cityAr: 'دبي', addressEn: 'Dubai Internet City, Building 17', addressAr: 'مدينة دبي للإنترنت، مبنى 17', phone: '+971 4 000 0000', email: 'dubai@example.com' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Global Offices',
      titleAr: 'مكاتبنا العالمية',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── More Hero Variants ────────────────────────────────────────────────────
  {
    id: 'hero-split',
    name: 'Hero Split Screen',
    nameAr: 'بانر الشاشة المنقسمة',
    description: 'Two-column split hero: text on left, hero image on right',
    descriptionAr: 'بانر رئيسي بعمودين: نص على اليسار وصورة رئيسية على اليمين',
    componentType: 'hero-split',
    category: 'Hero',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Build Something the World Will Remember',
      titleAr: 'ابنِ شيئاً سيتذكره العالم',
      subtitleEn: 'Award-Winning Platform',
      subtitleAr: 'منصة حائزة على جوائز',
      descriptionEn: 'Join over 50,000 teams that rely on our platform to plan, execute and deliver exceptional work every day.',
      descriptionAr: 'انضم إلى أكثر من 50,000 فريق يعتمد على منصتنا للتخطيط والتنفيذ وتسليم عمل استثنائي كل يوم.',
      primaryButtonLabelEn: 'Start for Free',
      primaryButtonLabelAr: 'ابدأ مجاناً',
      primaryButtonUrl: '/signup',
      secondaryButtonLabelEn: 'Book a Demo',
      secondaryButtonLabelAr: 'احجز عرضاً',
      secondaryButtonUrl: '/demo',
      image: '',
      imageAlt: '',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-24' },
  },
  {
    id: 'hero-minimal',
    name: 'Hero Minimal',
    nameAr: 'بانر بسيط',
    description: 'Clean centred headline, subtext and single CTA with no image',
    descriptionAr: 'عنوان مركزي نظيف ونص فرعي وزر إجراء واحد بلا صورة',
    componentType: 'hero-minimal',
    category: 'Hero',
    defaultData: {},
    defaultConfig: {
      taglineEn: '🚀 Now in public beta',
      taglineAr: '🚀 متاح الآن في النسخة التجريبية العامة',
      titleEn: 'The Operating System for Modern Teams',
      titleAr: 'نظام التشغيل للفرق الحديثة',
      descriptionEn: 'One platform to manage projects, track goals and communicate — so your team can focus on work that matters.',
      descriptionAr: 'منصة واحدة لإدارة المشاريع وتتبع الأهداف والتواصل — حتى يتمكن فريقك من التركيز على العمل المهم.',
      ctaLabelEn: 'Get Started — It\'s Free',
      ctaLabelAr: 'ابدأ — إنه مجاني',
      ctaUrl: '/signup',
      secondaryLabelEn: 'See how it works',
      secondaryLabelAr: 'شاهد كيف يعمل',
      secondaryUrl: '#demo',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-28' },
  },
  {
    id: 'hero-announcement',
    name: 'Announcement Hero',
    nameAr: 'بانر إعلان',
    description: 'Event or product launch announcement hero with countdown',
    descriptionAr: 'بانر رئيسي للإعلان عن حدث أو إطلاق منتج مع عداد تنازلي',
    componentType: 'hero-announcement',
    category: 'Hero',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Something Big is Coming',
      titleAr: 'شيء كبير قادم',
      descriptionEn: 'We are launching our next-generation platform on January 1st. Join the waitlist to get early access.',
      descriptionAr: 'نطلق منصتنا من الجيل التالي في الأول من يناير. انضم إلى قائمة الانتظار للحصول على وصول مبكر.',
      launchDate: '',
      ctaLabelEn: 'Join the Waitlist',
      ctaLabelAr: 'انضم إلى قائمة الانتظار',
      ctaUrl: '/waitlist',
      backgroundImage: '',
    },
    defaultStyling: { bgColor: 'bg-gray-900', paddingClass: 'py-32' },
  },

  // ── More Content Variants ─────────────────────────────────────────────────
  {
    id: 'content-rich-text',
    name: 'Rich Text Block',
    nameAr: 'كتلة نص منسّق',
    description: 'Full-width editorial rich text section with optional pull quote',
    descriptionAr: 'قسم نص تحريري منسّق كامل العرض مع اقتباس اختياري بارز',
    componentType: 'rich-text',
    category: 'Content',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Our Commitment to Excellence',
      titleAr: 'التزامنا بالتميز',
      bodyEn: '<p>We believe that great work comes from great culture. Since our founding, we have been committed to building a company where talented people can do the most meaningful work of their careers.</p><p>Every decision we make — from product design to customer support — is guided by a simple question: <em>does this create genuine value for the people we serve?</em></p>',
      bodyAr: '<p>نؤمن بأن العمل العظيم ينبع من ثقافة عظيمة. منذ تأسيسنا، التزمنا ببناء شركة يتمكن فيها الأشخاص الموهوبون من إنجاز أكثر الأعمال مغزىً في مسيرتهم المهنية.</p>',
      pullQuoteEn: 'We exist to make work better for people — not just more efficient.',
      pullQuoteAr: 'نحن موجودون لجعل العمل أفضل للناس — وليس فقط أكثر كفاءة.',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'content-split-image',
    name: 'Split Content + Image',
    nameAr: 'محتوى منقسم + صورة',
    description: 'Two-column section: rich text on one side, large image on the other',
    descriptionAr: 'قسم بعمودين: نص منسّق في جانب وصورة كبيرة في الآخر',
    componentType: 'split-content',
    category: 'Content',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Designed With People in Mind',
      titleAr: 'مصمم مع مراعاة الناس',
      descriptionEn: 'Every feature we build starts with a real user problem. We spend hours in research before writing a single line of code — because the best solutions come from a deep understanding of the challenge.',
      descriptionAr: 'كل ميزة نبنيها تبدأ بمشكلة مستخدم حقيقية. نقضي ساعات في البحث قبل كتابة سطر كود واحد — لأن أفضل الحلول تأتي من فهم عميق للتحدي.',
      image: '',
      imagePosition: 'right',
      ctaLabelEn: 'Learn Our Story',
      ctaLabelAr: 'تعرّف على قصتنا',
      ctaUrl: '/about',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-20' },
  },
  {
    id: 'content-icon-list',
    name: 'Icon Bullet List',
    nameAr: 'قائمة نقطية بأيقونات',
    description: 'Clean two-column icon and text list for benefits or requirements',
    descriptionAr: 'قائمة أيقونات ونص نظيفة بعمودين للمزايا أو المتطلبات',
    componentType: 'icon-list',
    category: 'Content',
    defaultData: {
      items: [
        { icon: '✅', textEn: 'No setup fees or long-term contracts', textAr: 'لا رسوم إعداد أو عقود طويلة الأمد' },
        { icon: '✅', textEn: 'Dedicated onboarding specialist included', textAr: 'متخصص إعداد مخصص مشمول' },
        { icon: '✅', textEn: 'SOC 2 Type II certified platform', textAr: 'منصة معتمدة SOC 2 Type II' },
        { icon: '✅', textEn: 'GDPR and CCPA compliant by default', textAr: 'متوافق مع GDPR و CCPA افتراضياً' },
        { icon: '✅', textEn: 'Free migration from any competitor', textAr: 'ترحيل مجاني من أي منافس' },
        { icon: '✅', textEn: '24/7 human support, not chatbots', textAr: 'دعم بشري على مدار الساعة، ليس روبوتات محادثة' },
      ],
    },
    defaultConfig: {
      titleEn: 'Everything Included, No Surprises',
      titleAr: 'كل شيء مشمول، لا مفاجآت',
      columns: 2,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── More Statistics Variants ───────────────────────────────────────────────
  {
    id: 'stats-with-chart',
    name: 'Stats with Progress Bars',
    nameAr: 'إحصائيات مع أشرطة التقدم',
    description: 'Animated statistics with visual progress bar indicators',
    descriptionAr: 'إحصائيات متحركة مع مؤشرات شريط التقدم المرئية',
    componentType: 'stats-progress',
    category: 'Statistics',
    defaultData: {
      items: [
        { labelEn: 'Customer Satisfaction', labelAr: 'رضا العملاء', value: 98, suffix: '%' },
        { labelEn: 'On-Time Delivery', labelAr: 'التسليم في الوقت المحدد', value: 95, suffix: '%' },
        { labelEn: 'Issue Resolution Rate', labelAr: 'معدل حل المشكلات', value: 99, suffix: '%' },
        { labelEn: 'Team Productivity Gain', labelAr: 'زيادة إنتاجية الفريق', value: 40, suffix: '%' },
      ],
    },
    defaultConfig: {
      titleEn: 'Measurable Results, Every Time',
      titleAr: 'نتائج قابلة للقياس في كل مرة',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },
  {
    id: 'stats-impact',
    name: 'Impact Numbers',
    nameAr: 'أرقام الأثر',
    description: 'Large bold impact numbers with supporting text on a coloured background',
    descriptionAr: 'أرقام أثر كبيرة وجريئة مع نص داعم على خلفية ملونة',
    componentType: 'stats-impact',
    category: 'Statistics',
    defaultData: {
      items: [
        { value: '10M+', labelEn: 'Tasks Completed', labelAr: 'مهمة مكتملة', descriptionEn: 'Across all customer workspaces', descriptionAr: 'عبر جميع مساحات عمل العملاء' },
        { value: '99.99%', labelEn: 'Uptime SLA', labelAr: 'وقت تشغيل SLA', descriptionEn: 'Guaranteed availability every month', descriptionAr: 'توفر مضمون كل شهر' },
        { value: '180+', labelEn: 'Countries Served', labelAr: 'دولة تخدمها', descriptionEn: 'Global presence across 6 continents', descriptionAr: 'حضور عالمي عبر 6 قارات' },
        { value: '4.9/5', labelEn: 'Average Rating', labelAr: 'متوسط التقييم', descriptionEn: 'Based on 25,000+ verified reviews', descriptionAr: 'بناءً على أكثر من 25,000 تقييم موثق' },
      ],
    },
    defaultConfig: {
      titleEn: 'The Numbers Speak for Themselves',
      titleAr: 'الأرقام تتحدث عن نفسها',
      bgColor: 'bg-gray-900',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-20' },
  },

  // ── More Cards Variants ───────────────────────────────────────────────────
  {
    id: 'cards-services',
    name: 'Services Cards',
    nameAr: 'بطاقات الخدمات',
    description: 'Service offering cards with icon, title, description and link',
    descriptionAr: 'بطاقات عرض الخدمات مع أيقونة وعنوان ووصف ورابط',
    componentType: 'services-cards',
    category: 'Cards',
    defaultData: {
      items: [
        { icon: '💡', titleEn: 'Strategy & Consulting', titleAr: 'الاستراتيجية والاستشارات', descriptionEn: 'We help you define where you want to go and build the roadmap to get there.', descriptionAr: 'نساعدك في تحديد وجهتك وبناء خارطة الطريق للوصول إليها.', linkEn: 'Learn more', linkAr: 'اعرف المزيد', linkUrl: '/services/strategy' },
        { icon: '🎨', titleEn: 'Design & UX', titleAr: 'التصميم وتجربة المستخدم', descriptionEn: 'Human-centred design that turns complex problems into elegant, intuitive experiences.', descriptionAr: 'تصميم متمحور حول الإنسان يحوّل المشكلات المعقدة إلى تجارب أنيقة وبديهية.', linkEn: 'Learn more', linkAr: 'اعرف المزيد', linkUrl: '/services/design' },
        { icon: '⚙️', titleEn: 'Engineering & Build', titleAr: 'الهندسة والتطوير', descriptionEn: 'Scalable, maintainable software built by engineers who care about craft.', descriptionAr: 'برنامج قابل للتوسع والصيانة، مبني من قبل مهندسين يهتمون بالحرفية.', linkEn: 'Learn more', linkAr: 'اعرف المزيد', linkUrl: '/services/engineering' },
        { icon: '📈', titleEn: 'Growth & Marketing', titleAr: 'النمو والتسويق', descriptionEn: 'Data-driven growth strategies that bring the right users to your product.', descriptionAr: 'استراتيجيات نمو مدفوعة بالبيانات تجلب المستخدمين المناسبين إلى منتجك.', linkEn: 'Learn more', linkAr: 'اعرف المزيد', linkUrl: '/services/growth' },
      ],
    },
    defaultConfig: {
      titleEn: 'What We Do',
      titleAr: 'ما نفعله',
      subtitleEn: 'End-to-end expertise across the product lifecycle',
      subtitleAr: 'خبرة شاملة عبر دورة حياة المنتج',
      columns: 2,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'cards-news-horizontal',
    name: 'Horizontal News Cards',
    nameAr: 'بطاقات أخبار أفقية',
    description: 'Stacked horizontal news/article cards with thumbnail on the side',
    descriptionAr: 'بطاقات أخبار/مقالات أفقية مكدّسة مع صورة مصغرة على الجانب',
    componentType: 'news-cards-horizontal',
    category: 'Cards',
    defaultData: {
      items: [
        { titleEn: 'Platform Named Top 10 SaaS Tool for 2025', titleAr: 'المنصة تُصنَّف ضمن أفضل 10 أدوات SaaS لعام 2025', categoryEn: 'Awards', categoryAr: 'الجوائز', date: '2025-01-18', image: '', slug: '/news/top10-saas' },
        { titleEn: 'New Integration: Connect with 500+ Apps', titleAr: 'تكامل جديد: اتصل بأكثر من 500 تطبيق', categoryEn: 'Product Update', categoryAr: 'تحديث المنتج', date: '2025-01-10', image: '', slug: '/news/integrations' },
        { titleEn: 'Our 2024 Year in Review', titleAr: 'مراجعتنا لعام 2024', categoryEn: 'Company', categoryAr: 'الشركة', date: '2024-12-31', image: '', slug: '/news/year-review' },
      ],
    },
    defaultConfig: {
      titleEn: 'Latest News',
      titleAr: 'آخر الأخبار',
      viewAllLabelEn: 'View All News',
      viewAllLabelAr: 'عرض جميع الأخبار',
      viewAllUrl: '/news',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── More Forms ────────────────────────────────────────────────────────────
  {
    id: 'form-waitlist',
    name: 'Waitlist Signup',
    nameAr: 'التسجيل في قائمة الانتظار',
    description: 'Email capture form for product launches and early access waitlists',
    descriptionAr: 'نموذج التقاط البريد الإلكتروني لإطلاق المنتجات وقوائم انتظار الوصول المبكر',
    componentType: 'waitlist-form',
    category: 'Forms',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Be the First to Know',
      titleAr: 'كن أول من يعلم',
      descriptionEn: 'Join 10,000+ people on the waitlist. We\'ll notify you the moment we launch.',
      descriptionAr: 'انضم إلى أكثر من 10,000 شخص في قائمة الانتظار. سنخطرك في اللحظة التي نطلق فيها.',
      placeholderEn: 'Enter your email address',
      placeholderAr: 'أدخل عنوان بريدك الإلكتروني',
      ctaLabelEn: 'Join the Waitlist',
      ctaLabelAr: 'انضم إلى قائمة الانتظار',
      privacyNoteEn: 'No spam, ever. Unsubscribe at any time.',
      privacyNoteAr: 'لا رسائل مزعجة أبداً. إلغاء الاشتراك في أي وقت.',
      bgColor: 'bg-gray-900',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-24' },
  },
  {
    id: 'form-multi-step',
    name: 'Multi-Step Form',
    nameAr: 'نموذج متعدد الخطوات',
    description: 'Guided multi-step form with progress indicator for registrations',
    descriptionAr: 'نموذج متعدد الخطوات موجّه مع مؤشر تقدم للتسجيلات',
    componentType: 'multi-step-form',
    category: 'Forms',
    defaultData: {
      steps: [
        { titleEn: 'Personal Info', titleAr: 'المعلومات الشخصية', fields: ['firstName', 'lastName', 'email'] },
        { titleEn: 'Organisation', titleAr: 'المنظمة', fields: ['company', 'role', 'teamSize'] },
        { titleEn: 'Your Needs', titleAr: 'احتياجاتك', fields: ['useCase', 'timeline', 'budget'] },
      ],
    },
    defaultConfig: {
      titleEn: 'Tell Us About Yourself',
      titleAr: 'أخبرنا عن نفسك',
      submitLabelEn: 'Submit Application',
      submitLabelAr: 'إرسال الطلب',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── More Dynamic ──────────────────────────────────────────────────────────
  {
    id: 'dynamic-jobs-feed',
    name: 'Job Openings Feed',
    nameAr: 'خلاصة فرص العمل',
    description: 'Dynamic list of current job openings with department filter',
    descriptionAr: 'قائمة ديناميكية بفرص العمل الحالية مع فلتر القسم',
    componentType: 'jobs-feed',
    category: 'Dynamic',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Join Our Team',
      titleAr: 'انضم إلى فريقنا',
      subtitleEn: 'We are always looking for exceptional people',
      subtitleAr: 'نبحث دائماً عن أشخاص استثنائيين',
      viewAllLabelEn: 'View All Openings',
      viewAllLabelAr: 'عرض جميع الوظائف',
      viewAllUrl: '/careers',
      count: 5,
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },
  {
    id: 'dynamic-members-feed',
    name: 'Member Profiles Feed',
    nameAr: 'خلاصة ملفات الأعضاء',
    description: 'Dynamic grid of member profiles from the members directory',
    descriptionAr: 'شبكة ديناميكية من ملفات الأعضاء من دليل الأعضاء',
    componentType: 'members-feed',
    category: 'Dynamic',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Our Members',
      titleAr: 'أعضاؤنا',
      count: 6,
      viewAllLabelEn: 'View Full Directory',
      viewAllLabelAr: 'عرض الدليل الكامل',
      viewAllUrl: '/members',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },

  // ── Media Extras ──────────────────────────────────────────────────────────
  {
    id: 'media-podcast',
    name: 'Podcast / Audio Section',
    nameAr: 'قسم البودكاست / الصوت',
    description: 'Featured podcast episodes with player and show notes',
    descriptionAr: 'حلقات بودكاست مميزة مع مشغّل وملاحظات البرنامج',
    componentType: 'podcast-section',
    category: 'Media',
    defaultData: {
      episodes: [
        { titleEn: 'The Future of Remote Work', titleAr: 'مستقبل العمل عن بُعد', durationEn: '42 min', durationAr: '42 دقيقة', dateEn: 'Jan 15, 2025', dateAr: '15 يناير 2025', audioUrl: '', image: '' },
        { titleEn: 'Building Culture at Scale', titleAr: 'بناء الثقافة على نطاق واسع', durationEn: '35 min', durationAr: '35 دقيقة', dateEn: 'Jan 8, 2025', dateAr: '8 يناير 2025', audioUrl: '', image: '' },
        { titleEn: 'Product-Led Growth Unpacked', titleAr: 'النمو بقيادة المنتج مُوضَّحاً', durationEn: '51 min', durationAr: '51 دقيقة', dateEn: 'Dec 29, 2024', dateAr: '29 ديسمبر 2024', audioUrl: '', image: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'The Weekly Podcast',
      titleAr: 'البودكاست الأسبوعي',
      descriptionEn: 'In-depth conversations with founders, builders and leaders redefining the future of work.',
      descriptionAr: 'محادثات متعمقة مع المؤسسين والبناة والقادة الذين يُعيدون تعريف مستقبل العمل.',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },
  {
    id: 'media-instagram-feed',
    name: 'Social Feed Grid',
    nameAr: 'شبكة خلاصة السوشيال ميديا',
    description: 'Instagram-style social media photo grid with profile CTA',
    descriptionAr: 'شبكة صور وسائل التواصل الاجتماعي بأسلوب انستغرام مع زر دعوة للمتابعة',
    componentType: 'social-feed',
    category: 'Media',
    defaultData: {
      posts: [
        { image: '', caption: '', likes: 0 },
        { image: '', caption: '', likes: 0 },
        { image: '', caption: '', likes: 0 },
        { image: '', caption: '', likes: 0 },
        { image: '', caption: '', likes: 0 },
        { image: '', caption: '', likes: 0 },
      ],
    },
    defaultConfig: {
      titleEn: 'Follow Us on Social',
      titleAr: 'تابعنا على السوشيال ميديا',
      platformHandle: '@yourhandle',
      profileUrl: 'https://instagram.com',
      ctaLabelEn: 'Follow for Updates',
      ctaLabelAr: 'تابع للحصول على التحديثات',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-16' },
  },

  // ── More Hero + Content Hybrids ───────────────────────────────────────────
  {
    id: 'about-intro',
    name: 'About / Mission Section',
    nameAr: 'قسم عن / رسالة',
    description: 'Company mission and values section with split layout',
    descriptionAr: 'قسم رسالة الشركة وقيمها بتخطيط منقسم',
    componentType: 'about-section',
    category: 'Content',
    defaultData: {
      values: [
        { icon: '❤️', titleEn: 'People First', titleAr: 'الناس أولاً', descriptionEn: 'We believe our greatest asset is our team and the customers we serve.', descriptionAr: 'نؤمن بأن أعظم أصولنا هو فريقنا والعملاء الذين نخدمهم.' },
        { icon: '🔍', titleEn: 'Radical Transparency', titleAr: 'الشفافية الجذرية', descriptionEn: 'We share what we know openly — with our team, our customers and the world.', descriptionAr: 'نشارك ما نعرفه بصراحة — مع فريقنا وعملائنا والعالم.' },
        { icon: '🌱', titleEn: 'Long-Term Thinking', titleAr: 'التفكير بعيد المدى', descriptionEn: 'We make decisions for the next decade, not the next quarter.', descriptionAr: 'نتخذ القرارات للعقد القادم، وليس للربع القادم.' },
      ],
    },
    defaultConfig: {
      titleEn: 'Our Mission',
      titleAr: 'رسالتنا',
      missionEn: 'To make meaningful work accessible to every person and organisation on the planet.',
      missionAr: 'جعل العمل الهادف متاحاً لكل شخص ومنظمة على هذا الكوكب.',
      image: '',
    },
    defaultStyling: { bgColor: 'bg-white', paddingClass: 'py-20' },
  },
  {
    id: 'awards-badges',
    name: 'Awards & Recognition',
    nameAr: 'الجوائز والتقدير',
    description: 'Showcase of awards, certifications and press mentions',
    descriptionAr: 'عرض الجوائز والشهادات والذكر في الصحافة',
    componentType: 'awards-section',
    category: 'Content',
    defaultData: {
      awards: [
        { titleEn: 'Best Product 2024', titleAr: 'أفضل منتج 2024', issuerEn: 'TechCrunch Awards', issuerAr: 'جوائز TechCrunch', year: '2024', image: '' },
        { titleEn: 'Top 50 SaaS Companies', titleAr: 'أفضل 50 شركة SaaS', issuerEn: 'G2 Crowd', issuerAr: 'G2 Crowd', year: '2024', image: '' },
        { titleEn: 'Innovation Leader', titleAr: 'رائد الابتكار', issuerEn: 'Gartner', issuerAr: 'Gartner', year: '2023', image: '' },
        { titleEn: 'Editor\'s Choice', titleAr: 'اختيار المحررين', issuerEn: 'Product Hunt', issuerAr: 'Product Hunt', year: '2023', image: '' },
      ],
      pressMentions: [
        { outletEn: 'Forbes', outletAr: 'فوربس', quoteEn: '"The platform every growing team needs"', quoteAr: '"المنصة التي يحتاجها كل فريق متنامٍ"', url: '' },
        { outletEn: 'Wired', outletAr: 'وايرد', quoteEn: '"Redefining how work gets done"', quoteAr: '"إعادة تعريف كيفية إنجاز العمل"', url: '' },
        { outletEn: 'Fast Company', outletAr: 'فاست كومباني', quoteEn: '"One of the most innovative companies of 2024"', quoteAr: '"إحدى الشركات الأكثر ابتكاراً في 2024"', url: '' },
      ],
    },
    defaultConfig: {
      titleEn: 'Recognised by the Best',
      titleAr: 'معترف بها من قبل الأفضل',
    },
    defaultStyling: { bgColor: 'bg-gray-50', paddingClass: 'py-16' },
  },
  {
    id: 'cta-newsletter-inline',
    name: 'Inline CTA + Newsletter',
    nameAr: 'دعوة للعمل + نشرة مدمجة',
    description: 'Side-by-side CTA text and newsletter signup in one compact banner',
    descriptionAr: 'نص دعوة للعمل والاشتراك في النشرة جنباً إلى جنب في بانر مدمج',
    componentType: 'cta-newsletter',
    category: 'Forms',
    defaultData: {},
    defaultConfig: {
      titleEn: 'Stay in the Loop',
      titleAr: 'ابقَ على اطلاع',
      descriptionEn: 'Get the latest updates, articles and resources delivered straight to your inbox.',
      descriptionAr: 'احصل على أحدث التحديثات والمقالات والموارد مباشرة إلى صندوق البريد الخاص بك.',
      placeholderEn: 'Your email address',
      placeholderAr: 'عنوان بريدك الإلكتروني',
      ctaLabelEn: 'Subscribe Now',
      ctaLabelAr: 'اشترك الآن',
      privacyEn: 'We respect your privacy. Unsubscribe anytime.',
      privacyAr: 'نحترم خصوصيتك. إلغاء الاشتراك في أي وقت.',
      bgColor: 'bg-indigo-600',
      textColor: 'text-white',
    },
    defaultStyling: { paddingClass: 'py-14' },
  },

];

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  'Hero', 'Features', 'Content', 'Cards', 'Statistics', 'Media', 'Testimonials', 'Team', 'Blog', 'Portfolio', 'Pricing', 'Gallery', 'Video', 'Steps', 'Logos', 'Tabs', 'Comparison', 'Maps', 'Forms', 'Dynamic', 'Custom',
];
